### ISSUE TITLE
Error refreshing session

### ISSUE THREAD

**Issue by geschenkwald** [karfly/chatgpt_telegram_bot#1]
I got an error if i try to start docker image.
First everything seems to bei fine:

`~/projects/chatgpt_telegram_bot# docker compose up --build
[+] Building 28.7s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim                                                                                    20.7s
 => [internal] load build context                                                                                                                      0.0s
 => => transferring context: 4.99kB                                                                                                                    0.0s
 => [1/7] FROM docker.io/library/python:3.8-slim@sha256:e7eab22979e5698f18432aca3cc54d91b025282640b869cf17e4b87fb612144d                               0.0s
 => CACHED [2/7] RUN apt-get update                                                                                                                    0.0s
 => CACHED [3/7] RUN apt-get install -y python3 python3-pip python-dev build-essential python3-venv                                                    0.0s
 => CACHED [4/7] RUN mkdir -p /chatgpt_telegram_bot                                                                                                    0.0s
 => [5/7] ADD . /chatgpt_telegram_bot                                                                                                                  0.0s
 => [6/7] WORKDIR /chatgpt_telegram_bot                                                                                                                0.0s
 => [7/7] RUN pip3 install -r requirements.txt                                                                                                         7.2s
 => exporting to image                                                                                                                                 0.6s
 => => exporting layers                                                                                                                                0.6s
 => => writing image sha256:d36bbb10bf9ba5cd2a12b4fcba237773c6d5c18abd75748ca9162dbfd2a18235                                                           0.0s
 => => naming to docker.io/library/chatgpt_telegram_bot_chatgpt_telegram_bot                                                                           0.0s
[+] Running 1/0
 ⠿ Container chatgpt_telegram_bot  Recreated                                                                                                           0.1s`

But then this occurs:
`Attaching to chatgpt_telegram_bot
chatgpt_telegram_bot  | Error refreshing session
chatgpt_telegram_bot  | <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span>[...]=</span></div></div></body></html>`

what can i do to solve this?

**Comment by karfly** [comment]
Hi! OpenAI changed the API to ChatGPT, so it doesn’t work for now…

**Comment by karfly** [comment]
I switched the code to GPT-3.5 engine. Try it now
