### ISSUE TITLE
voice message recognition is not working

### ISSUE THREAD

**Issue by 7enChan** [karfly/chatgpt_telegram_bot#102]
Voice message recognition is not working, and I have already rebuilt the Docker image.
I sent a voice message, but the bot didn't respond at all

**Comment by karfly** [comment]
What exactly not working?

**Comment by 7enChan** [comment]
> 
Sending voice messages on the bot provided by you will be converted into a text message, but my bot doesn't respond after sending a voice message.

**Comment by karfly** [comment]
Did you update the code and rebuilt your docker?

**Comment by 7enChan** [comment]
> Did you update the code and rebuilt your docker?

Thank you very much for your reply. My problem has been solved. I rebuilt Docker, but I did not update the code.
Your project is great and very beginner-friendly 👍
