### ISSUE TITLE
Responding to messages is slow

### ISSUE THREAD

**Issue by 1491928274** [karfly/chatgpt_telegram_bot#105]
It takes a long time to reply. Is there any way to shorten the reply time?

**Comment by clemsau** [comment]
Are you using the author's bot or a self hosted version ? 
In the latter case, are you sure it's not your server or the network ?

**Comment by 1491928274** [comment]
@clemsau It is hosted by myself, and the api is hosted on the Hong Kong server. After hearing what you said, I found that this may be the reason. Thanks for the reminder!
