### ISSUE TITLE
How to add multiple users in config.yml?

### ISSUE THREAD

**Issue by augus-br** [karfly/chatgpt_telegram_bot#107]
I tried add using `allowed_telegram_usernames: [exampleid1, exampleid2]` and also `allowed_telegram_usernames: [exampleid1: true, exampleid2: true]` but both ways stop and restart mongo and chat processes. What is the correct way to separate users?

**Comment by 1491928274** [comment]
I also encountered the same issue as you, and later found out that it might be the username, not the User ID. I hope the author can add User IDs instead of using usernames, as usernames may be duplicated, but User IDs will not be duplicated.

**Comment by clemsau** [comment]
The username used by the telegram lib to filter users is your `@`, it cannot be replicated by other users, so it's working fine :+1:

**Comment by augus-br** [comment]
There was some confusion on my part. The username must be placed instead of the ID. I think @1491928274 meant that usernames can be changed, removed and others can take it for themselves. The User ID is unique and non-transferable. Another problem is that not everyone has a username. It would be great if @karfly could update the program to accept ID's instead of usernames.

**Comment by 1491928274** [comment]
not all users have usernames@clemsau, but every person has a user ID, which is unique. I hope the author can consider using user IDs.

**Comment by clemsau** [comment]
Right, It seems doable with the telegram lib. 
You can work on it, I might also submit a PR for review.

**Comment by karfly** [comment]
PR on supporting user_ids will be great.
For example, if you pass str value to `allowed_telegram_usernames` it is interpreted as username. If you pass int it is interpreted as user_id.

**Comment by clemsau** [comment]
Great method to work with it, I'll send a PR soon

**Comment by karfly** [comment]
@clemsau 
Thank you one more time! ❤️ 

As an active participant and contributor, please check this [discussion](https://github.com/karfly/chatgpt_telegram_bot/issues/114)
