### ISSUE TITLE
Use Telegram editMessageText API to stream the reply

### ISSUE THREAD

**Issue by lqhl** [karfly/chatgpt_telegram_bot#114]
Improve user experiment by using the editMessageText API to return the partial results.

A demo in https://twitter.com/wsvn53/status/1633799055167066113

Related #105

**Comment by hamed-ehtesham** [comment]
Hi, it would be great if you could also include the text formatting similar to the demo mentioned. Thank you in advance!

**Comment by karfly** [comment]
I've just implemented message streaming feature. It appeared to be a really hard task. Big thanks to @gkorepanov for helping!

@gkorepanov @lqhl @hamed-ehtesham @CCCAUCHY @ronpay and other
Guys, it would be really great if you helped me with testing this feature! I'm not going to push it to **main** until it has been tested by someone else 😌

It's on the `stream` branch. Here's [PR](https://github.com/karfly/chatgpt_telegram_bot/pull/130).

**Comment by karfly** [comment]
@gkorepanov @lqhl @hamed-ehtesham @CCCAUCHY @ronpay @ngn999 @clemsau
Short demo of streaming (just to motivate you to test 😄)

![Streaming demo](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzliNGE0MDhlNjk5MjhlYWZlNTUxZjUzOWRhMTg3Mzc3NjA1Nzk0OCZjdD1n/ImOVlowJPXlTQMmhKH/giphy.gif)

**Comment by ngn999** [comment]
I have deployed the stream branch to fly.io, and it is working perfectly.

**Comment by lqhl** [comment]
@karfly I deployed it on a google cloud VM using docker-compose, and it works perfectly.
Thank you for your work!

**Comment by flymin** [comment]
In my case, openai api always returns leading "\n\n" as the first message. This leads to error in tg: `Reason: Message must be non-empty`.
<img width="675" alt="image" src="https://user-images.githubusercontent.com/28671430/225334764-1c705b1c-04a6-4fd5-aa2d-0ec1dcd85e66.png">

Am I alone?

**Comment by karfly** [comment]
@flymin it's a bug. I'll fix it in a while

**Comment by flymin** [comment]
> @flymin it's a bug. I'll fix it in a while

Thank you. After fixing this, other parts on the branch work well by my side.

**Comment by flymin** [comment]
I tested locally and the functionality is good.

**Comment by karfly** [comment]
MERGED 🎉

**Comment by Sweetshotby** [comment]
What is needed to create streaming? Maybe there is material to study?
