### ISSUE TITLE
[Discussion] Will there be any deployment methods available for Kubernetes in the future?

### ISSUE THREAD

**Issue by SpiffyEight77** [karfly/chatgpt_telegram_bot#120]
Currently, I have a k3s cluster running my self-hosted services. I'm used to splitting the services and deploying them into the cluster. In the future, would there be a chance to provide a separate docker image for deploying the ChatGPT Telegram bot?

**Comment by clemsau** [comment]
There's already a docker image in the project, so you could theoretically build the image:

`docker build -t <username>/<imagename>:<tag> .`

Then push it to the public registry:

`docker push <username>/<imagename>:<tag>`

It would then be available publically. **BUT**, don't do that with your private API key in it, your telegram token & your private username (config variables in the `config.yml`).

You would also need to spin a mongodb on the side to run with the project, but without a way to store securely the config variables, I don't think it is possible rn.

Shouldn't the API keys, and maybe the allowed users list, be in the env variables ? @karfly 
It would also respect the [12 factor app](https://12factor.net/config) principle better

**Comment by SpiffyEight77** [comment]
Thank you for your reply. As you mentioned, the problem I am currently facing is that I cannot pass ``openai_api_key``, ``telegram_token``, and ``allowed_telegram_usernames`` to the container through environment variables when running the ``docker run`` command. 

Therefore, if possible, I think it would be better to put variables like ``openai_api_key``, ``telegram_token``, ``MONGODB_URI``, and ``allowed_telegram_usernames`` in the ``config.env`` file or mount the ``config.yml`` file into the container.
