### ISSUE TITLE
Zero tokens

### ISSUE THREAD

**Issue by vbs-0** [karfly/chatgpt_telegram_bot#126]
Something went wrong during completion. Reason: You exceeded your current quota, please check your plan and billing details.
Got this message after deployment could please help me sir

**Comment by bigsky77** [comment]
Hey - I am getting this error as well.  :(

**Comment by bigsky77** [comment]
I am dumb.  Had to upgrade to paid and restart docker.  FIXED

**Comment by lomeat** [comment]
How do upgrade to paid? I don't see anything about payment in repo. Btw, I need to integrate my own system for payment and dunno know where its checking

**Comment by karfly** [comment]
You need to upgrade your OpenAI account to paid one.
@lomeat write me on Telegram (@karfly)
