### ISSUE TITLE
Can you support the image generation function of the new api

### ISSUE THREAD

**Issue by ylimly** [karfly/chatgpt_telegram_bot#128]
GPT3.5 api
https://platform.openai.com/docs/guides/images/image-generation-beta

**Comment by karfly** [comment]
It's the next feature to come!

**Comment by clemsau** [comment]
I had this [PR](https://github.com/karfly/chatgpt_telegram_bot/pull/111) pending. Haven't tested it yet though

**Comment by karfly** [comment]
Hi! I've just added support of DALLE 2. Please update the code (git pull) and choose 👩‍🎨 Artist mode with `/mode` command.

@ylimly @clemsau @yautat123321 @mr-wh1tehat @ngn999 @secsilm @davbaster @Cristia15830179
