### ISSUE TITLE
Ras Pi Installation Issues

### ISSUE THREAD

**Issue by Majidyalfani** [karfly/chatgpt_telegram_bot#133]
Im trying to install it on Ras Pi and getting an error... Seems mongo DB won't install. will it support Ras Pi?

docker-compose --env-file config/config.env up --build

**Comment by Majidyalfani** [comment]
sudo docker-compose --env-file config/config.env up --build
Pulling mongo (mongo:latest)...
latest: Pulling from library/mongo
ERROR: no matching manifest for linux/arm/v8 in the manifest list entries

**Comment by boi4** [comment]
For me it worked by replaceing `mongo:latest` with `mongo:bionic` in the docker compose file
