### ISSUE TITLE
Message gets cut off

### ISSUE THREAD

**Issue by jinhoe** [karfly/chatgpt_telegram_bot#134]
Hi, the message gets cut off. I don't think I hit the text limit of telegram yet.
Could be connection issue between telegram and openai, or my server couldn't handle the load? Any idea?
![IMG_0167](https://user-images.githubusercontent.com/20474213/225527493-aefef360-2382-4875-b8be-c124c4f2d0d4.jpg)

**Comment by jinhoe** [comment]
Great work by the way, so far the most complete integration I can find!

**Comment by jinhoe** [comment]
Looks like the problem is solved by increased my server ram from 512 MB to 1 GB. Yay!

**Comment by clemsau** [comment]
That's weird if the server's RAM makes the bot send an incomplete answer :thinking: 
Were you using the recently added progressive completion ?

**Comment by jinhoe** [comment]
> That's weird if the server's RAM makes the bot send an incomplete answer 🤔
> Were you using the recently added progressive completion ?

Not sure what is progressive completion, but I'm using the latest release - Real-time Message Streaming.

**Comment by clemsau** [comment]
I meant real-time message streaming yeah. I'll look into what might have caused this issue, and a possible fix.
