### ISSUE TITLE
how to close auto reply on group chat? 

### ISSUE THREAD

**Issue by EsqerYasen** [karfly/chatgpt_telegram_bot#138]
how to close auto reply on group chat? 
only reply when i @bot.

**Comment by zhangzheng1214** [comment]
I have encountered a similar question and added filters in `bot.py` to ensure that the bot replies to messages sent to @bot and incoming messages reply to the bot. It would be greatly appreciated if the author could add some configuration to facilitate this filtering process.

**Comment by karfly** [comment]
All group chat features will be added soon

**Comment by karfly** [comment]
Hi! I've just added support of group chats. Please update the code (git pull) and send /help_group_chat to bot to get instructions (I also added video instruction there)

@EsqerYasen @ericz15 @clemsau
