### ISSUE TITLE
Multiple API keys

### ISSUE THREAD

**Issue by ignatyb** [karfly/chatgpt_telegram_bot#139]
Is it possible to use multiple API keys?

**Comment by clemsau** [comment]
In what way do you expect the rotation of the multiple API key to work ? 
Why exactly do you want that ?

**Comment by b4sh1t1** [comment]
it may be usefull for termination key/account, it will be alternative api in case.

**Comment by clemsau** [comment]
@b4sh1t1 what behavior do you expect with multiple API keys ?

**Comment by Cristia15830179** [comment]
I think that @ignatyb is referring to : 
- you can register any time for a new account, and get those 18$ free credit;
- or this can be used by multiple users, each user, has their own API key, and each of them is setting their API, depending on which is using it.
I don't know, I am throwing ideas.

**Comment by karfly** [comment]
I think that in both cases it's better to easily redeploy the bot or setup 2 different bots
