### ISSUE TITLE
allowed_telegram_usernames: not working, or what i'm doing wrong?

### ISSUE THREAD

**Issue by KvizadSaderah** [karfly/chatgpt_telegram_bot#14]
As far as i understood, only username in here, can use bot? "allowed_telegram_usernames"?

I was writing it with @, and without.

And while checking it on second account, could freely use bot.

**Comment by karfly** [comment]
I've just double checked it, and it works fine.
In `config/config.yml` I have line `allowed_telegram_usernames: ["@karfly"]` and bot is only available for me.

What exact line in config do you have?

**Comment by KvizadSaderah** [comment]
looks like i didn't use "", let me check

**Comment by KvizadSaderah** [comment]
1. Found out 'why' it didn't worked on me - 🤦 - because it was needed to rebuild docker-compose. :done:
2. Added that line, where it should printing ? (can't find it, but think it's not that important now) :almost_done:

**Comment by karfly** [comment]
"prompt_start" is not supposed to be sent to user. It's an internal thing to "configure" GPT-3 as an assistant.

**Comment by KvizadSaderah** [comment]
aaaaa, i got it... thanks
