### ISSUE TITLE
current dialog is too long

### ISSUE THREAD

**Issue by Adiolph** [karfly/chatgpt_telegram_bot#144]
Hey, after tens messages with the bot, it says that:
```
✍️ Note: Your current dialog is too long, so your first message was removed from the context.
Send /new command to start new dialog
```

Does this limit come from OpenAI API? 
If not, can you add settings to adjust the number for this limit? Thanks!

**Comment by karfly** [comment]
Hi, it's an OpenAPI limit (4097 tokens). Dialog context is cut if such limit is met
