### ISSUE TITLE
Add code formatting

### ISSUE THREAD

**Issue by yaroslavyaroslav** [karfly/chatgpt_telegram_bot#145]
ChatGPT formats code examples in its answer with MD markup. e.g. \`inline command\` and \`\`\`rust rust multiline code \`\`\` and so on.

Telegram also capable to mark some parts of a message as a code, without sytax highlighting though. 

Anyway even this realisation would be useful, as tg allows to copy such code alike message parts with one click.

Here's the message from the bot. All std::thread and rust code block could be formatted in telegram as well.

    In Rust, multithreading can be implemented using the `std::thread` module. Here's a simple example:

    ```rust
    use std::thread;

    fn main() {
        let handle = thread::spawn(|| {
            // thread code goes here
            println!("Hello from thread!");
        });

        // wait for thread to finish
        handle.join().unwrap();

        println!("Main thread exiting.");
    }
    ```

    In this example, we create a new thread using `thread::spawn()`. The argument to `thread::spawn()` is a closure containing the code that will run in the new thread. In this case, we just print a message to the console.

    After the thread is created, we use the `join()` method on the `handle` object to wait for the thread to finish. This ensures that the main thread doesn't exit before the new thread has finished running.

    It's important to note that Rust threads are not meant to be used for parallelism by default. Rust's ownership and borrowing system make it difficult to safely share data between threads. Instead, Rust encourages the use of message-passing concurrency using channels.

UPD with example.

**Comment by karfly** [comment]
Code formatting is available in Code Assistant mode https://github.com/karfly/chatgpt_telegram_bot/blob/main/config/chat_modes.yml#L16

**Comment by yaroslavyaroslav** [comment]
My bad, thanks!
