### ISSUE TITLE
requirements error

### ISSUE THREAD

**Issue by TelePuryang** [karfly/chatgpt_telegram_bot#146]
how to solve it, thank you 

> `
[+] Building 131.6s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 462B                                                                              0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 2B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim                                                1.8s
 => [1/7] FROM docker.io/library/python:3.8-slim@sha256:54ece633a6094e4eb66f6f8bcdff20355c4cc60c63a4f7787a2e3a46  0.0s
 => [internal] load build context                                                                                 0.0s
 => => transferring context: 2.77kB                                                                               0.0s
 => CACHED [2/7] RUN apt-get update                                                                               0.0s
 => CACHED [3/7] RUN apt-get install -y python3 python3-pip python-dev build-essential python3-venv ffmpeg        0.0s
 => CACHED [4/7] RUN mkdir -p /code                                                                               0.0s
 => CACHED [5/7] ADD . /code                                                                                      0.0s
 => CACHED [6/7] WORKDIR /code                                                                                    0.0s
 => ERROR [7/7] RUN pip3 install -r requirements.txt                                                            129.7s
------
 > [7/7] RUN pip3 install -r requirements.txt:
#0 22.00 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcba9313d00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/python-telegram-bot/
#0 42.51 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcba93139a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/python-telegram-bot/
#0 63.53 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcba931bbb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/python-telegram-bot/
#0 85.55 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcba931bc40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/python-telegram-bot/
#0 109.6 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcba931bdf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/python-telegram-bot/
#0 129.6 ERROR: Could not find a version that satisfies the requirement python-telegram-bot[rate-limiter]==20.1 (from versions: none)
#0 129.6 ERROR: No matching distribution found for python-telegram-bot[rate-limiter]==20.1
------
failed to solve: process "/bin/sh -c pip3 install -r requirements.txt" did not complete successfully: exit code: 1`

**Comment by clemsau** [comment]
Are you running it locally when connected to the internet ?

Does it work if you add `network_mode: "host"` to the `chatgpt_telegram_bot` service in the `docker-compose.yml` file ?
