### ISSUE TITLE
command /stop or new /new

### ISSUE THREAD

**Issue by CCCAUCHY** [karfly/chatgpt_telegram_bot#148]
Sometimes chatgpt is very slow. But if I use another bot to start a new dialog, my chatgpt API can response fast.
Sometimes chatgpt is so slow that I lose interest and I don't want to recieve any new message from the bot.
A new command `/stop` which can stop the current dialog should be helpful.
I prefer command ` /new` which can stop the current dialog and then start a new dialog instead of waiting.

**Comment by Cristia15830179** [comment]
> 

Great idea, but if you use `/new`, it will not recollect the previous messages. In this case, a `/stop` would be better, as it will stop the current task only.

**Comment by karfly** [comment]
Nice idea, I'll think how to implement it
