### ISSUE TITLE
restrictions on chatgpt in group.

### ISSUE THREAD

**Issue by b4sh1t1** [karfly/chatgpt_telegram_bot#149]
Hi,

Thanks for the awesome project! 

I have 3 question; 
1. how to set different language than english in the bot ? to be the official language if someone interactive with the bot.
2. how to make list for allowed people inside group, and how set $0.3 per account for public usage (not more than 5-10 conversation).
3. how to set bitcoin + monero for payments in the bot ?

Thanks.

**Comment by hvanmegen** [comment]
The original author has a paid version for that; this repository isn't that same code. You will have to build in that functionality yourself.
