### ISSUE TITLE
Why the same question is still very different from the answer of official web？

### ISSUE THREAD

**Issue by TelePuryang** [karfly/chatgpt_telegram_bot#151]
The official chatgpt3.5 model has been updated synchronously, why the direction and content of the answer are different. Please tell me how to restore the default model configuration, no need to define personal settings to achieve the same response effect as the official website. grateful!

**Comment by hvanmegen** [comment]
This telegram bot uses a different system message as you can see in `config/chat_modes.yml`

Since it is not exactly know what ChatGPT uses for prompt_start, the answer will always be different.

**Comment by karfly** [comment]
There is some randomness both in telegram bot and official chatgpt site, so you can't get the exactly the same answers.
