### ISSUE TITLE
Is it possible to add different chats like the official web

### ISSUE THREAD

**Issue by appar-sc** [karfly/chatgpt_telegram_bot#152]
Just throwing idea here, I will be working on this feature in my fork as well.

1. For each chat, it won't have timeout
2. Able to manage (delete, rename, create, switch) chat via Telegram commands

**Comment by karfly** [comment]
Hmm. Do you think it'll be convenient to use such a complex non-linear structure of chats in Telegram?

**Comment by appar-sc** [comment]
Oh what does complex non-linear structure mean?

**Comment by karfly** [comment]
That you have multiple chat dialog in one Telegram dialog
