### ISSUE TITLE
last message does not respond

### ISSUE THREAD

**Issue by TelePuryang** [karfly/chatgpt_telegram_bot#153]
If the last message does not respond, it cannot end or open a new message, and can only wait for the last message to be processed.

**Comment by Cristia15830179** [comment]
I can confirm, the same thing is happening to me also.

**Comment by Iambabyninja** [comment]
Ну и для меня тоже(

**Comment by Iambabyninja** [comment]
Need /cancel command

**Comment by artyone** [comment]
Yeah. The same. Sometimes the answer does not come and you have to wait for 5 minutes until the message arrives: Something went wrong during the completion. Reason: Error when communicating with OpenAI

**Comment by ngn999** [comment]
Same problem here, I have to restart the bot.

**Comment by ominaevid** [comment]
Confirm.

**Comment by ominaevid** [comment]
Confirm.
