### ISSUE TITLE
New Feature suggested: Add markdown rendering

### ISSUE THREAD

**Issue by Monophonic1983** [karfly/chatgpt_telegram_bot#156]
The bot would be great if it supports markdown rendering, so that the chat would be more streamlined.

**Comment by wenzelt** [comment]
try implementing 
`bot.telegram.sendMessage(GROUP_ID, 'I have *bold text*', { parse_mode: "MarkdownV2" });` in your bot.py and opening a pull request.

**Comment by karfly** [comment]
Markdown is already supported and used in Code Assistant mode

**Comment by karfly** [comment]
I tried MARKDOWNV2 in bot, but it worked unpredictably
