### ISSUE TITLE
New (future?) feature: Switching between different modules

### ISSUE THREAD

**Issue by SharkDrakeSkyrade** [karfly/chatgpt_telegram_bot#158]
As we all know, OpenAI is already giving away GPT-4 API keys via waitlist. However the pricing for its usage is much higher then the GPT-3.5-turbo, which makes it a more expensive option for simple tasks that 3.5-turbo is already being great at..

Would it be possible to make a new chat mode, which could switch between such modules? As a user, I would love to have an option to switch between those 2 modules without restarting the docker

**Comment by karfly** [comment]
Right now you can already switch between different model with `/settings` command
