### ISSUE TITLE
Simplify bot changes (and restarts) by using VOLUME mounts for Docker containers

### ISSUE THREAD

**Issue by hvanmegen** [karfly/chatgpt_telegram_bot#166]
Currently, changes to the bot require a docker-compose build to be triggered since the config directory is copied as part of the Dockerfile setup. This makes it more difficult for contributors to make changes and slows down the development process.

I propose updating the Dockerfile and docker-compose.yml to use VOLUME mounts for the `./bot/` and `./config/` directories, allowing for simpler container restarts and easier bot changes.

I will submit a pull request with the changes.

**Comment by karfly** [comment]
@hvanmegen I looked at your PR – nice job!
Tbh, I don't like to make volume forwarding in production code. But it's a pretty big feature to be able iterating faster.

I personally prefer to create `docker-compose.dev.yml` config in which I make volume forwarding (`{HOST_REPO_HOST}`:`/code`) and then run with command `docker compose --env-file config/config.env -f docker-compose.dev.yml up -d`

**Comment by hvanmegen** [comment]
@karfly You're clearly a professional and a skilled docker user, however a lot of people will be not be and be relying on using tools such as Portainer, Kitematic, Docker Swarm, Rancher, etc. which don't easily handle adding environment variables to the commands.. this would defy the purpose of quickly restarting the docker container for the widest possible audience. (I wish it were different too).

Would having the changes I made commented in the original docker-compose.yml & a mention in the README.md on how to enable them for easy and faster restarts be a better solution? Because I'll submit a new pull request with exactly that if you agree to accept it in that form.

**Comment by karfly** [comment]
@hvanmegen, yeap!
It'll be great if people could find clear instructions on how to develop with faster debug rates
