### ISSUE TITLE
PRoblem with API openai configuration

### ISSUE THREAD

**Issue by Emanuele98Pr** [karfly/chatgpt_telegram_bot#172]
Hello i have problem with the configuration of the API. when i set correctly the API i have the problem on telegram that say to me that is incorrect. Can you help me? or do you have the same problem?

In telegram: Something went wrong during completion. Reason: Incorrect API key provided: sk-ojvYj***************************************MDe5. You can find your API key at https://platform.openai.com/account/api-keys.

Openai (https://platform.openai.com/account/api-keys)
OpenAI API
An API for accessing new AI models developed by OpenAI

**Comment by karfly** [comment]
Incorrect OpenAI API key
