### ISSUE TITLE
GPT4 Diailog message is reduced to zero

### ISSUE THREAD

**Issue by areochi** [karfly/chatgpt_telegram_bot#175]
Hey, thanks for the update. When I try to select the chat GPT-4 and write any message, even "hello", my telegram bot replies me:

Something went wrong during completion. Reason: Dialog messages is reduced to zero, but still has too many tokens to make completion. How do i fix that? Just wanna know - should i have chat GPT-4 API key to access for that settings mode?

**Comment by sedatabase** [comment]
Yes you should get a GPT4 api from the address below.

https://openai.com/waitlist/gpt-4-api
