### ISSUE TITLE
chatgpt telegram bot on Raspberry Pi Zero 2

### ISSUE THREAD

**Issue by hblink** [karfly/chatgpt_telegram_bot#178]
i am failing with this:
#0 707.0 ERROR: Could not build wheels for tiktoken, which is required to install pyproject.toml-based projects

during docker-compose build, the rest of requirements.txt finishes fine, any suggestion as to why would be greatly appreciated

**Comment by karfly** [comment]
Hi, you need to explore, why tiktoken lib doesn't work on Pi (maybe you can write issue in tiktoken github)
