### ISSUE TITLE
The build is successful, prompting that I do not have permission, please help me to solve it

### ISSUE THREAD

**Issue by xiangchu95** [karfly/chatgpt_telegram_bot#181]
![image](https://user-images.githubusercontent.com/110237853/227772173-4befa933-826f-46b1-871e-576c2dad5e59.png)
How to use the MongoDB database deployed in the local environment to deploy applications

**Comment by karfly** [comment]
Never met such error. Did you google it?

**Comment by xiangchu95** [comment]
In the source code, I didn't find how to connect to the existing local database. I tried to modify the "mongodb_uri" in the source code, but found that it didn't work.

**Comment by karfly** [comment]
No, it can't be the cause

**Comment by xiangchu95** [comment]
How should I configure a remote MongoDB connection in the project? I don't seem to have found a place where I can configure environment variables or parameters.
