### ISSUE TITLE
Stable Diffusion? 

### ISSUE THREAD

**Issue by areochi** [karfly/chatgpt_telegram_bot#183]
What are your thoughts on adding stable diffusion image generation to the bot?

**Comment by clemsau** [comment]
What service would you want stable diffusion to be served with ? bc idk if you are missunderstanding with dalle which is served by openAI. Stable diffusion is an open source image generation model, it can be served from many services but not from openAI

Talking about dalle, I had a working PR for image generation hanging for some time: https://github.com/karfly/chatgpt_telegram_bot/pull/111

**Comment by karfly** [comment]
DALLE-2 will be added soon
