### ISSUE TITLE
Auto join message larger than 4096 characters before sending it ChatGPT API server?

### ISSUE THREAD

**Issue by jckefan** [karfly/chatgpt_telegram_bot#184]
I'm often pasting code snippets which are larger 4096 characters to the bot server. Commanding the bot to wait for the other part of code seldom works. I would appreciate it if you could look into this issue. Thank you for the continued support to the bot, by the way.

**Comment by karfly** [comment]
It's a narrow use case and I'm not going to implement this, because it would highly affect the UX (you need to ask for confirmation if all you messages are sent)
