### ISSUE TITLE
where can i deploy this code?

### ISSUE THREAD

**Issue by razipv** [karfly/chatgpt_telegram_bot#185]
i tried to run it in codescpace. it works. but after sometime it stops responding in  telegram bot. where else i can deploy this?

**Comment by Mata23K77** [comment]
google cloud

**Comment by karfly** [comment]
I use AWS. Also I like to use DigitalOcean (in other projects)

**Comment by razipv** [comment]
Both require payment?

**Comment by karfly** [comment]
I think so, yes. But they have some free options

**Comment by danielatlarge** [comment]
You can get a 4 dollar host at DigitalOcean in the USA.
