### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by snegodick** [karfly/chatgpt_telegram_bot#19]
After startup i got error in telegram messages:
Something went wrong during completion. Reason: 'NoneType' object is not subscriptable

**Comment by caiski** [comment]
Went into the same issue.
How did u get over it ? @snegodick

**Comment by snegodick** [comment]
> Went into the same issue. How did u get over it ? @snegodick

I already forgot, sorry :) But the problem was on my side - check DNS or something like that.

**Comment by caiski** [comment]
> > Went into the same issue. How did u get over it ? @snegodick
> 
> I already forgot, sorry :) But the problem was on my side - check DNS or something like that.

Thanks for the tip. I'll check it. :)

**Comment by snegodick** [comment]
> Went into the same issue. How did u get over it ? @snegodick

LOW DISK SPACE! check your free space, this shit eat them

**Comment by caiski** [comment]
> 

Well, my free space are enormouse. So not the disk.

I just waited for several minutes after docker compose up, and retry the telegram bot, it worked.
Still confused what standed in the way. Maybe i'll dig into it when i have time.

**Comment by AmrAbuelhamd** [comment]
I had the same issue, started chatting without sending `/new` was the issue
