### ISSUE TITLE
Markdown in Code Assistant Not Rendering?

### ISSUE THREAD

**Issue by chk86** [karfly/chatgpt_telegram_bot#192]
Hello, 

I'm having an issue with the Code Assistant rendering in Markdown. I'm using both Telegram Desktop and Telegram iOS. With all of the code the bot is giving me, I'm seeing the actual three backticks followed by the code and then the three backticks again. If I copy and paste the same exact code back into the same chat with the bot, telegram renders it as Markdown. 

Any suggestions? 

I did note that markdownv2 is recommended by Telegram in their docs as markdown is considered legacy. Is that a possible reason why the bot isn't rendering the code in markdown? 

Thanks!!

CK

**Comment by chk86** [comment]
Here's what I'm seeing: 
![image](https://user-images.githubusercontent.com/8128522/228536941-47a94704-0efd-45e6-a082-a6ab949497e0.png)

And if I copy and paste the code back into the bot, here's what I see:
![image](https://user-images.githubusercontent.com/8128522/228537087-9b06de0a-daec-4b01-97ef-d39e9a730049.png)

**Comment by chk86** [comment]
I've continued testing it all day, and have been seeing the same results, however, for reasons I'm unclear on, it's now parsing markdown correctly.

**Comment by chk86** [comment]
> Do you use MARKDOWN or MARKDOWNV2?

Markdown. It's weird, cause I tried it again since I closed this and it showed the back ticks. I tried Markdownv2 and it also behaved unpredictably like you said in the other thread.

**Comment by jayagami** [comment]
same with me, markdown not rendering.
