### ISSUE TITLE
chatgpt-4 not working

### ISSUE THREAD

**Issue by ivanarya007** [karfly/chatgpt_telegram_bot#193]
chatgpt4 is not working sharing this problem please see and fix

![Screenshot (3)](https://user-images.githubusercontent.com/97018175/228558261-f9acd25b-e394-432e-a197-7669df03d7d2.png)

**Comment by pandability** [comment]
> chatgpt4 is not working sharing this problem please see and fix

Maybe, you don't have access to GPT-4 API.

**Comment by hvanmegen** [comment]
@ivanarya007 you most probably don't have access to the GPT-4 API.
