### ISSUE TITLE
Sending a voice message at /start

### ISSUE THREAD

**Issue by danielatlarge** [karfly/chatgpt_telegram_bot#195]
I would like to send an AI crafted voice message at the beginning of /start
I've been having a lot of fun with some of the Ai generated voices. 
Here is the code snippet for /start

```
async def start_handle(update: Update, context: CallbackContext):
    await register_user_if_not_exists(update, context, update.message.from_user)
    user_id = update.message.from_user.id
    
    db.set_user_attribute(user_id, "last_interaction", datetime.now())
    db.start_new_dialog(user_id)
    
    reply_text = """Hello, and welcome to my bot! \n\n"""
    reply_text += HELP_MESSAGE

    await update.message.reply_text(reply_text, parse_mode=ParseMode.HTML)
```
How could I send the /start message and then send an mp3 file as a voice message?
Wanted to create something like this: await send_voice(chat_id=chat_id, voice="https://example.com/hello.mp3")
Can anyone steer me in the right direction?

**Comment by karfly** [comment]
You just need to call [send_voice](https://docs.python-telegram-bot.org/en/stable/telegram.bot.html#telegram.Bot.send_voice) in the end of `start_handle`

**Comment by danielatlarge** [comment]
I have not worked before with the Telegram module and appreciate the help!

I have tried adding the following at the end:
attempt 1
`async context.bot.send_voice(chat_id=update.message.chat_id, voice="https://example.com/telegram/bot.ogg")`
attempt 2
`  
voice_url = 'https://example.com/telegram/bot.ogg' 
bot = context.bot
chat_id = update.message.chat_id
bot.send_voice(chat_id=chat_id, voice=voice_url)`

Thanks!
