### ISSUE TITLE
Did someone mangaged to add submenu for the bot? 

### ISSUE THREAD

**Issue by Eylon12345** [karfly/chatgpt_telegram_bot#198]
will be a lot simpler to interact with after adding more chat modes..

**Comment by karfly** [comment]
What do you mean by submenu?

**Comment by Eylon12345** [comment]
![telegram_media_library_demo](https://user-images.githubusercontent.com/121553761/229055287-50113c6b-b173-47cf-ba3e-ac38596e18dc.gif)
so you could really customize the user experience when playing with chat modes..

**Comment by karfly** [comment]
Hmm, what would you add to Chat Mode submenu?

**Comment by Eylon12345** [comment]
games/music/text categories and so on..
