### ISSUE TITLE
Something went wrong during completion. Reason: You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by ivanarya007** [karfly/chatgpt_telegram_bot#199]
![Screenshot (4)](https://user-images.githubusercontent.com/97018175/228915514-e925e16b-5c4b-4742-8fdc-dfd50ac5ad7e.png)

Please Fix This issue

**Comment by karfly** [comment]
It means, that your exceeded you OpenAI API quota. You need to pay for it
