### ISSUE TITLE
Usage in Super Groups

### ISSUE THREAD

**Issue by AaronAbraham420** [karfly/chatgpt_telegram_bot#20]
Tried using the bot by adding it on a group yet it doesn't respond to any commands other than Private Chats

`

> An exception was raised while handling an update
> update = {
>   "update_id": 329041365,
>   "message": {
>     "chat": {
>       "id": -1001479127404,
>       "type": "supergroup",
>       "username": "daboyclub",
>       "title": "The Boy's🕺&💃Girl's Club"
>     },
>     "text": "/new@clubwaifubot",
>     "group_chat_created": false,
>     "entities": [
>       {
>         "length": 17,
>         "type": "bot_command",
>         "offset": 0
>       }
>     ],
>     "new_chat_members": [],
>     "reply_to_message": {
>       "chat": {
>         "id": -1001479127404,
>         "type": "supergroup",
>         "username": "daboyclub",
>         "title": "The Boy's🕺&💃Girl's Club"
>       },
>       "group_chat_created": false,
>       "entities": [],
>       "new_chat_members": [],
>       "new_chat_photo": [],
>       "message_id": 53913,
>       "delete_chat_photo": false,
>       "caption_entities": [],
>       "date": 1669044355,
>       "supergroup_chat_created": false,
>       "photo": [],
>       "channel_chat_created": false,
>       "from": {
>         "is_bot": false,
>         "username": "AaronOmoriChan",
>         "first_name": "Aaron",
>         "last_name": "Chan",
>         "id": 836019393,
>         "language_code": "en"
>       }
>     },
>     "new_chat_photo": [],
>     "message_id": 62391,
>     "delete_chat_photo": false,
>     "caption_entities": [],
>     "date": 1674797813,
>     "supergroup_chat_created": false,
>     "photo": [],
>     "channel_chat_created": false,
>     "from": {
>       "is_bot": false,
>       "username": "AaronOmoriChan",
>       "first_name": "Aaron",
>       "last_name": "Chan",
>       "id": 836019393,
>       "language_code": "en"
>     }
>   }
> }
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 945, in process_update
>     await coroutine
>   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 135, in handle_update
>     return await self.callback(update, context)
>   File "bot/bot.py", line 149, in new_dialog_handle
>     await update.message.reply_text(f"{chatgpt.CHAT_MODES[chat_mode]['welcome_message']}", parse_mode=ParseMode.HTML)
>   File "/usr/local/lib/python3.8/site-packages/telegram/_message.py", line 784, in reply_text
>     return await self.get_bot().send_message(
>   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 238, in decorator
>     result = await func(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 637, in send_message
>     return await self._send_message(  # type: ignore[return-value]
>   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 253, in _send_message
>     result = await super()._send_message(
>   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 346, in _send_message
>     result = await self._post(
>   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 310, in _post
>     return await request.post(
>   File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 160, in post
>     result = await self._request_wrapper(
>   File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 319, in _request_wrapper
>     raise BadRequest(message)
> telegram.error.BadRequest: Replied message not found

`

The messaging worked for a while on the groupchat while I mentioned with the command on a particular Group

**Comment by karfly** [comment]
It's originally designed to be used in 1-to-1 chat, not in groups.
