### ISSUE TITLE
DALL·E

### ISSUE THREAD

**Issue by djx2726889** [karfly/chatgpt_telegram_bot#202]
Is it possible to integrate openAI's image generation model DALL·E and directly return images through the Telegram chat window?

**Comment by vnt87** [comment]
Yes, I believe @clemsau has a pending PR that does just that
https://github.com/karfly/chatgpt_telegram_bot/pull/111/files

**Comment by karfly** [comment]
Hi! I've just added support of DALLE 2. Please update the code (git pull) and choose 👩‍🎨 Artist mode with /mode command.

@djx2726889 @vnt87 @maxgashkov @yellavhtaed
