### ISSUE TITLE
GPT-4

### ISSUE THREAD

**Issue by xiaoyuer0408** [karfly/chatgpt_telegram_bot#203]
Prompt when selecting GPT-4: Something went wrong during completion. Reason: The model: `gpt-4` does not exist

**Comment by Iambabyninja** [comment]
you don't have access to GPT-4 API.

**Comment by xiaoyuer0408** [comment]
> you don't have access to GPT-4 API.

May I ask what conditions are required to access the gpt-4 API

**Comment by vnt87** [comment]
You need to be either a ChatGPT Plus subscriber or in join the OpenAI API waitlist. I've been in the waitlist for a month and it's still not available for me yet.

**Comment by xiaoyuer0408** [comment]
> You need to be either a ChatGPT Plus subscriber or in join the OpenAI API waitlist. I've been in the waitlist for a month and it's still not available for me yet.

ok thanks for the reminder

**Comment by danielatlarge** [comment]
@vnt87 Careful. I keep reading this comment that if you are a Plus subscriber you get access to the API for gpt-4. It isn't true. You do not automatically get access. I paid today and turns out that I still don't have access to the API. Requested again access.

**Comment by vnt87** [comment]
@danielatlarge I see, thanks for the clarification.
