### ISSUE TITLE
Do not expose mongo to public

### ISSUE THREAD

**Issue by yijia2413** [karfly/chatgpt_telegram_bot#21]
It works fine with the following lines deleted.

https://github.com/karfly/chatgpt_telegram_bot/blob/main/docker-compose.yml#L9
https://github.com/karfly/chatgpt_telegram_bot/blob/main/docker-compose.yml#L29

If someone deploy on public cloud, it will be danger...

**Comment by lovecastle** [comment]
```
root@wowz:/home/wowz.co/chatgpt# docker-compose --env-file config/config.env up --build
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mongo.ports contains an invalid type, it should be an array
services.mongo_express.ports contains an invalid type, it should be an array
```

I have this error after deleting these 2 lines

**Comment by DimaRazb** [comment]
Same error if I comment these lines here.
