### ISSUE TITLE
Docker is stuck at the startup stage

### ISSUE THREAD

**Issue by SanchezMorg** [karfly/chatgpt_telegram_bot#214]
Hi, this is my first time working with doker. When installing files on docker servers, I ran into a problem. 

I enter the command
`docker-compose --env-file config/config.env up --build`

The installation process is underway, and at some point these lines
`Step 9/16 : RUN apt-get update
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (windows/amd64) and no specific platform was requested
 ---> Running in 4db8026681ad
Err:1 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update' returned a non-zero code: 4294967295: failed to shutdown container: container 4db8026681add3541e8fc049a35bd1a9335caf03d9cb9cad7249378f103770b3 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 4db8026681add3541e8fc049a35bd1a9335caf03d9cb9cad7249378f103770b3 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)
PS M:\doctor\chatgpt_telegram_bot>`

My operating system is windows 10
how to solve it?

**Comment by shev-pro** [comment]
When building your docker image, it's important to ensure that you specify the correct platform. This can be done by using the command "docker build --platform linux/amd64" or by setting the environment variable "DOCKER_DEFAULT_PLATFORM" to "linux/amd64" before running your docker-compose command. By doing so, you can ensure that your images are built for the correct platform and can run efficiently on the intended system but virtualized on windows.
