### ISSUE TITLE
Simplify adding new modes

### ISSUE THREAD

**Issue by dmitrybabich** [karfly/chatgpt_telegram_bot#218]
Adding/modifying a new mode is a complicated process, as modes are not reloaded on-the-fly. Would it be possible to provide a way to always re-fetch the latest version of `chat_modes.yml` so the full bot restart is not needed?

**Comment by karfly** [comment]
@dmitrybabich 
From my experience it's a pretty time consuming task to create good chat mode. So the time spent on creating chat mode is >> than docker reload => there is no reason to have hot re-fetch of chat modes.
