### ISSUE TITLE
Errno 13 during build

### ISSUE THREAD

**Issue by Costyyy** [karfly/chatgpt_telegram_bot#219]
Hi, I'm trying to build the docker container but I'm getting the following error:

#0 9.062 Setting up python3.9-minimal (3.9.2-1) ...
#0 9.156 Traceback (most recent call last):
#0 9.156   File "/usr/lib/python3.9/py_compile.py", line 215, in <module>
#0 9.156     sys.exit(main())
#0 9.156   File "/usr/lib/python3.9/py_compile.py", line 207, in main
#0 9.156     compile(filename, doraise=True)
#0 9.156   File "/usr/lib/python3.9/py_compile.py", line 172, in compile
#0 9.156     importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
#0 9.156   File "<frozen importlib._bootstrap_external>", line 126, in _write_atomic
#0 9.156 PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/__pycache__/__future__.cpython-39.pyc.140117268685184'
#0 9.158 dpkg: error processing package python3.9-minimal (--configure):
#0 9.158  installed python3.9-minimal package post-installation script subprocess returned error exit status 1
#0 9.171 Errors were encountered while processing:
#0 9.171  python3.9-minimal
#0 9.212 E: Sub-process /usr/bin/dpkg returned an error code (1)
ERROR: failed to solve: executor failed running [/bin/sh -c apt-get install -y python3 python3-pip python-dev build-essential python3-venv ffmpeg]: exit code: 100
ERROR: Service 'chatgpt_telegram_bot' failed to build : Build failed

I've tried changing permissions to the __pycache__ folder and the owner but that didn't work. Also tried running docker compose with sudo but the error still persists. 
Not sure what else to do.

**Comment by znake77** [comment]
In the Dockerfile you may add this before `RUN apt-get update`

`RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak && sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list`

It's seems that repositories moved. Repositories for older releases that are not supported (like 11.04, 11.10 and 13.04) get moved to an archive server. There are repositories available at http://old-releases.ubuntu.com/.

**Comment by znake77** [comment]
So maybe first try restarting Docker.

`sudo service docker restart` or `sudo /etc/init.d/docker restart`

For this to work, Docker should have been working fine in the past. If you never had Docker working in the first place, you probably have a different issue.

**Comment by Costyyy** [comment]
@znake77 That didn't work. I tried also to completely remove docker and it's plugins and reinstall it but I still got the same error. I managed to fix the issue by using docker desktop instead.
