### ISSUE TITLE
Increase message memory limit?

### ISSUE THREAD

**Issue by DingoAtNight** [karfly/chatgpt_telegram_bot#221]
Is there a way to increase the amount of messages allowed in one chat?

 I know 20 is generous enough, but I'd be interested to see how long it's able to remember details from earlier in the conversation. 

Any help is really appreciated, and I hope you're having a good day!

**Comment by karfly** [comment]
There is a limit which comes from OpenAI models context limit. There is a way to avoid it with retrieval techniques. Maybe I'll add it in next releases.
