### ISSUE TITLE
MongoDB data is getting wiped

### ISSUE THREAD

**Issue by magicnov** [karfly/chatgpt_telegram_bot#222]
For some reason, after some time (1-2 days, no service reboots), the database in mongo is deleted. Does the chat bot application provide for auto-cleaning of the database or is it due to incorrect docker compose settings?

**Comment by karfly** [comment]
No, such behaviour is strange. Maybe it's stored somewhere on disk, where it's being wiped?

**Comment by magicnov** [comment]
> No, such behaviour is strange. Maybe it's stored somewhere on disk, where it's being wiped?

Problem were resolved after updating to the latest commit. Thank you for your work!
