### ISSUE TITLE
You exceeded your current quota

### ISSUE THREAD

**Issue by pashazeit** [karfly/chatgpt_telegram_bot#225]
Hi all. started the bot. I write a message, and in response to me - "Something went wrong during completion. Reason: You exceeded your current quota, please check your plan and billing details."
How to fix it?
Thanks

**Comment by AlanRvk** [comment]
Check you account on OpenAI , you have billing options linked to your API. You probably put a limit, you just have to increase it.

**Comment by pashazeit** [comment]
> Check you account on OpenAI , you have billing options linked to your API. You probably put a limit, you just have to increase it.

I have to buy tokens to use the bot?
