### ISSUE TITLE
Can't access mongo database page

### ISSUE THREAD

**Issue by TelePuryang** [karfly/chatgpt_telegram_bot#229]
The new version cannot access the database background page through the server public network address plus the port of mongo express.

I want to know how to access the database page, the previous version can be accessed normally through the public network ip plus port, thanks!

**Comment by BilalZahidShah** [comment]
yeah, brother if ya found out the way you can also tell me how to configure the Mongo DB there is no documentation about that my bot is working fine without the MongoDB.

**Comment by TelePuryang** [comment]
> Has been resolved. In the docker-compose.yml file, delete the local addresses of mongo and mongo-express before port mapping. Now the default setting is that it can only be accessed through the local ip address. After deleting the ip address, it can be accessed through the public network. The author may have set it this way for security reasons.

**Comment by krimtsev** [comment]
> > Has been resolved. In the docker-compose.yml file, delete the local addresses of mongo and mongo-express before port mapping. Now the default setting is that it can only be accessed through the local ip address. After deleting the ip address, it can be accessed through the public network. The author may have set it this way for security reasons.

Could you attach an example file?

**Comment by TelePuryang** [comment]
> 
version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - ${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - /root/mongodbdata:/data/db
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
