### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by lovecastle** [karfly/chatgpt_telegram_bot#231]
I removed the old version, but failed to build the new version. I don't know how to fix, please help!

It stucked at: 

> Get:325 http://deb.debian.org/debian bullseye/main amd64 python3-venv amd64 3.9.2-3 [1188 B]
> Get:326 http://deb.debian.org/debian bullseye/main amd64 va-driver-all amd64 2.10.0-1 [15.3 kB]
> Get:327 http://deb.debian.org/debian bullseye/main amd64 vdpau-driver-all amd64 1.4-3 [8540 B]
> Get:328 http://deb.debian.org/debian bullseye/main amd64 xdg-user-dirs amd64 0.17-2 [53.8 kB]
> Fetched 258 MB in 2s (106 MB/s)
> E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/t/tiff/libtiff5_4.2.0-1%2bdeb11u3_amd64.deb  404  Not Found [IP: 146.75.30.132 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ERROR: Service 'chatgpt_telegram_bot' failed to build: The command '/bin/sh -c apt-get install -y python3 python3-pip python-dev build-essential python3-venv ffmpeg' returned a non-zero code: 100

![Screen Shot 2023-04-13 at 15 44 55](https://user-images.githubusercontent.com/27679560/231705388-169d9686-9dc8-4d15-bb25-6f62f0873b3d.png)

**Comment by tianmk520** [comment]
我也是，怎么解决
