### ISSUE TITLE
Encountered errors while bringing up the project. Mango

### ISSUE THREAD

**Issue by SanchezMorg** [karfly/chatgpt_telegram_bot#237]
I ran into a problem. Info below
`Creating mongo ... error                                                                                                
ERROR: for mongo  Cannot create container for service mongo: user declined directory sharing M:\doctor\chatgpt_telegram_bot\mongodb

ERROR: for mongo  Cannot create container for service mongo: user declined directory sharing M:\doctor\chatgpt_telegram_bot\mongodb
ERROR: Encountered errors while bringing up the project.`

how to fix?

**Comment by lifeindarkside** [comment]
Install mongo manualy 
[https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/#packages](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/#packages)

Then Start MongoDB 
`sudo systemctl start mongod`

after this 

`sudo systemctl status mongod`

then send here result
