### ISSUE TITLE
having a mode "God"

### ISSUE THREAD

**Issue by hblink** [karfly/chatgpt_telegram_bot#249]
With all due respect, I would like to express my concern regarding the inclusion of a God mode in your bot. While I understand that humor may have been the intention, I find the presence of such a feature to be inappropriate and potentially disrespectful to those who hold differing beliefs.

Please understand that my perspective is not rooted in pedantry or religious fervor, but rather in a desire for mutual respect and consideration of diverse perspectives. I believe that we should strive to maintain a professional and inclusive environment in all aspects of our interactions, including the use of language and programming features.

I appreciate your attention to this matter and thank you for your commitment to maintaining a respectful and thoughtful platform.

**Comment by karfly** [comment]
Thank you for your comment. Replaced God mode with Motivator

**Comment by miqonee** [comment]
> With all due respect, I would like to express my concern regarding the inclusion of a God mode in your bot. While I understand that humor may have been the intention, I find the presence of such a feature to be inappropriate and potentially disrespectful to those who hold differing beliefs.
> 
> Please understand that my perspective is not rooted in pedantry or religious fervor, but rather in a desire for mutual respect and consideration of diverse perspectives. I believe that we should strive to maintain a professional and inclusive environment in all aspects of our interactions, including the use of language and programming features.
> 
> I appreciate your attention to this matter and thank you for your commitment to maintaining a respectful and thoughtful platform.

my mode
nireg:
  name: FindWater
  welcome_message: Hey bruh, help me find water and chickens.
  prompt_start: |
    You are a monkey who is lost in the desert, help me find water and chickens.
  parse_mode: html
