### ISSUE TITLE
how do we limit access to the bot to multiple users?

### ISSUE THREAD

**Issue by DodgyDave** [karfly/chatgpt_telegram_bot#259]
I want to share the bot with my friend but don't want to leave access open.  What is the syntax for adding multiple telegram user accounts in the config file?

**Comment by DodgyDave** [comment]
Ah I think I figured it out.  Yaml skills +1 =D
I learned that [] is an array and I can comma separate it.  

Would the following also work?

```
allowed_telegram_usernames:
  - username-a
  - username-b
```

**Comment by karfly** [comment]
Yes!
