### ISSUE TITLE
Provide deployment instructions for AWS lambda or other cloud options

### ISSUE THREAD

**Issue by wedontdozero** [karfly/chatgpt_telegram_bot#260]
Will you please provide instructions on how to deploy on the cloud? I have tried to learn for a few weeks but cannot get it to work. 
Also it seems like using webhooks would be more efficient, but will it break the message streaming feature?
Thank you!

**Comment by zilluk** [comment]
I have succesfully deployed it to the cloud using GPT4 to explain the steps to me. Have you tried that?

**Comment by wedontdozero** [comment]
Yes I have, I managed to deploy to EC2 but could not get the webhooks to work with lambda. Where did you deploy on? @zilluk

**Comment by zilluk** [comment]
> Yes I have, I managed to deploy to EC2 but could not get the webhooks to work with lambda. Where did you deploy on? @zilluk

First off, I am a complete newbie so I don't understand what all those words (webhooks, lambda) mean, although I just asked GPT to explain it to me...so far I am only using the EC2 instance. Am I missing something? What is the advantage of also using lambda?
