### ISSUE TITLE
what happen?

### ISSUE THREAD

**Issue by qiuyuhz** [karfly/chatgpt_telegram_bot#27]
![image](https://user-images.githubusercontent.com/116573969/216813515-7010e5bf-b4c2-48a5-ac8b-623fdd2caa3c.png)

**Comment by karfly** [comment]
Please show your `allowed_telegram_usernames` parameter from `config/config.yml`

**Comment by qiuyuhz** [comment]
> Please show your `allowed_telegram_usernames` parameter from `config/config.yml`

[1890383430]
thanks

**Comment by qiuyuhz** [comment]
> > Please show your `allowed_telegram_usernames` parameter from `config/config.yml`
> 
> [1890383430] thanks

i think it should be ["1890383430"]

**Comment by qiuyuhz** [comment]
I set it to [], and now the result is:
![image](https://user-images.githubusercontent.com/116573969/216816241-89965568-7006-4273-a4f5-a42cdcd70e93.png)

**Comment by karfly** [comment]
Are you using the latest version?

**Comment by qiuyuhz** [comment]
> Are you using the latest version?

yes.
now  it works very well, I did not do anything.
