### ISSUE TITLE
Applying changes in chat_models.yml and config.yml

### ISSUE THREAD

**Issue by yelloduxx** [karfly/chatgpt_telegram_bot#273]
There was a good suggestion here #167  to restart the bot by "docker-compose restart" command to apply changes. Seems it was not included in updates. How can we restart the bot to apply the changes then?
Would be glad to see the PR mentioned above in use.

Thanks in advance.

**Comment by cywale** [comment]
use `docker-compose up --build`

**Comment by karfly** [comment]
Yes, as @cywale said, you need to restart the bot:
```bash
docker-compose --env-file config/config.env up --build
```
