### ISSUE TITLE
Feature Suggestion: Limit some functions to certain users in a group

### ISSUE THREAD

**Issue by OpsHelp** [karfly/chatgpt_telegram_bot#286]
Only allow specific users to:

- Check balance
- Change mode
- Change settings

This would be useful when the bot is part of a group and you just want specific users to be able to do certain things, and allow others just to talk to the bot

**Comment by bigbabybubble** [comment]
async def post_init(application: Application):
    private_commands = [
        BotCommand("/", ""),
        ....
    ]

    group_commands = [
        BotCommand("/", ""),
        ....
    ]
    await application.bot.set_my_commands(private_commands, scope=BotCommandScopeAllPrivateChats())
    await application.bot.set_my_commands(group_commands, scope=BotCommandScopeAllGroupChats())
