### ISSUE TITLE
not convenient to change allowed_telegram_usernames

### ISSUE THREAD

**Issue by akynazh** [karfly/chatgpt_telegram_bot#29]
When I add new users to allowed_telegram_usernames, I have to recreate image.

Consider add a volume like: config:/root/config, then I can just restart the container by `docker-compose up -d`.

or is there a better way?

**Comment by karfly** [comment]
I prefer not to link code and configs with host filesystem, because such approach is error prone. For me it's more convenient to rebuild the image after changing code or configs.

**Comment by akynazh** [comment]
Alright, it's ok.
