### ISSUE TITLE
Running multiple bots with docker

### ISSUE THREAD

**Issue by yueyin97** [karfly/chatgpt_telegram_bot#292]
Hi, I tried to run a second bot on my computer and changed the port and the container name accordingly, but the second bot won't run and show below error, what should I do?

`raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27018: [Errno -3] Temporary failure in name resolution, Timeout: 30s, Topology Description: <TopologyDescription id: 6473c0f5796f930b8d40f625, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27018: [Errno -3] Temporary failure in name resolution')>]>`

This is the config of my second bot:

version: "3"

services:
  mongo-ethan:
    container_name: mongo-ethan
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27018}:${MONGODB_PORT:-27018}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth

  chatgpt_telegram_bot-ethan:
    container_name: chatgpt_telegram_bot-ethan
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo-ethan

  mongo_express-ethan:
    container_name: mongo-express-ethan
    image: mongo-express:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_PORT:-8082}:${MONGO_EXPRESS_PORT:-8082}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-ethan
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27018}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot-ethan
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo-ethan

**Comment by karfly** [comment]
Currently "multiple bots on a single machine" is not supported
