### ISSUE TITLE
bot not working

### ISSUE THREAD

**Issue by abdulrehman6** [karfly/chatgpt_telegram_bot#298]
![Untitled11](https://github.com/karfly/chatgpt_telegram_bot/assets/32044325/2e23184b-8e67-4274-bc24-fcf86cee83bc)

**Comment by abdulrehman6** [comment]
![Untitled23](https://github.com/karfly/chatgpt_telegram_bot/assets/32044325/39ca31d6-6a49-4638-a128-2f9272d5ffbc)

**Comment by kevzy** [comment]
let it finish downloading all dependecies takes about 3mins
