### ISSUE TITLE
Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - Ports are not available: exposing port TCP 127.0.0.1:27017 -> 0.0.0.0:0: listen tcp 127.0.0.1:27017: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### ISSUE THREAD

**Issue by abdulrehman6** [karfly/chatgpt_telegram_bot#299]
![mongo error](https://github.com/karfly/chatgpt_telegram_bot/assets/32044325/b068dbce-ebb7-4ad6-94b2-bb69c7a49c1f)

my config.env file have below code;

# local path where to store MongoDB
MONGODB_PATH=./mongodb
# MongoDB port
MONGODB_PORT=27017

# Mongo Express port
MONGO_EXPRESS_PORT=8081
# Mongo Express username
MONGO_EXPRESS_USERNAME=username
# Mongo Express password
MONGO_EXPRESS_PASSWORD=password

**Comment by TheOneironaut** [comment]
Happens to me too. Did you find a solution?
