### ISSUE TITLE
python-dev issue 

### ISSUE THREAD

**Issue by cookins** [karfly/chatgpt_telegram_bot#308]
Days ago i was able to build from docker file normally, but now getting error, that python-dev seems gone from repository...

From compose log:

RUN apt-get install -y python3 python3-pip python-
dev build-essential python3-venv ffmpeg:
#0 8.087 Reading package lists...
#0 19.19 Building dependency tree...
#0 20.30 Reading state information...
#0 20.40 Package python-dev is not available, but is referred to by another pack
age.
#0 20.40 This may mean that the package is missing,
has been obsoleted, or
#0 20.40 is only available from another source
#0 20.40 However the following packages replace it:
#0 20.40   python-dev-is-python3
#0 20.40
#0 20.41 E: Package 'python-dev' has no installation candidate
------
failed to solve: process "/bin/sh -c apt-get install -y python3 python3-pip pyth
on-dev build-essential python3-venv ffmpeg" did not
complete successfully: exit
code: 100

**Comment by Fl0p** [comment]
change to python3-dev

**Comment by Fl0p** [comment]
Here fix - https://github.com/karfly/chatgpt_telegram_bot/pull/311
