### ISSUE TITLE
How to enable in group and disable in private?

### ISSUE THREAD

**Issue by Tiande** [karfly/chatgpt_telegram_bot#310]
Hi, can I just use it in group for ALL users, and only respond to SPERCIFIC users?

Thanks!

**Comment by Tiande** [comment]
I try to use group id, but no use.

**Comment by Tiande** [comment]
I have edited the file “bot/bot.py” in line 677, and **it works**:

`user_filter = filters.User(username=usernames) | filters.User(user_id=user_ids) | filters.Chat(chat_id=-xxxxx) | filters.Chat(chat_id=-xxxxx) `

*how to find chat_id:
Invite @RawDataBot to your group.
Upon joining it will output a JSON file where your chat id will be located at message.chat.id.

**Comment by Fl0p** [comment]
https://github.com/karfly/chatgpt_telegram_bot/pull/312
