### ISSUE TITLE
Suddenly, he started sending an error. 

### ISSUE THREAD

**Issue by MrCatBoss** [karfly/chatgpt_telegram_bot#318]
After some time, I began to give such an error. ![IMG_20230622_134034.jpg](https://github.com/karfly/chatgpt_telegram_bot/assets/60252110/48999e78-7bec-4652-bcd5-515e86d7235a)

![IMG_20230622_134101.jpg](https://github.com/karfly/chatgpt_telegram_bot/assets/60252110/3c1b996f-3d1e-48fc-8d42-6c96148e7300)

**Comment by Serg4y** [comment]
anybody solve this problem?

**Comment by karfly** [comment]
I see many users face this problem, but I can't reproduce it on my machine.
Can you give me your setup in config.yml and list steps which comes to this problem?

I think that the error comes from telegram when you try to send empty message. But the hell it can be empty – I don't understand.

**Comment by Serg4y** [comment]
just enable_message_streaming: false, and bot working!
