### ISSUE TITLE
Use custom v1/chat/completions endpoint

### ISSUE THREAD

**Issue by hogmac** [karfly/chatgpt_telegram_bot#319]
Can this customization be added to the bot?

**Comment by karfly** [comment]
Can you please clarify your request?

**Comment by hogmac** [comment]
Just like you have defined  openai_api_key: "", do you think can add openai_key_base: ""   value to the config?
Sometimes we are in need of using a custom endpoint other than oai default one and will be great to add it that way for ease of use.

**Comment by hogmac** [comment]
In my case is because of having the api behind a proxy because of ip restrictions.   I know of other people making similar configs for their specific reasons. 

These are the ones I know - just check if that's feasible to you.

**Comment by karfly** [comment]
Thank you for your answer. I'll think how to add to the code (or you can send a PR if you want)

**Comment by vital121** [comment]
thats great thanks
