### ISSUE TITLE
Deploy with Portainer issue

### ISSUE THREAD

**Issue by glinko** [karfly/chatgpt_telegram_bot#320]
Recently I started receiving the error described here https://github.com/karfly/chatgpt_telegram_bot/issues/318 (empty messages)
So I decided to redeploy it.
I try to deploy using Portainer and get an error:

Traceback (most recent call last):
  File "bot/bot.py", line 33, in <module>
    import config
  File "/code/bot/config.py", line 8, in <module>
    with open(config_dir / "config.yml", 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/code/config/config.yml'

So the part "/code/" seems wrong.
I think I have to rewrite the path to the config files somewhere in bot.py 
Any suggestions?

**Comment by mxwmnn** [comment]
Did you rename the files in config/config.example.yml to config.yml?
