### ISSUE TITLE
Where is the docker image?

### ISSUE THREAD

**Issue by Jacky-Bruse** [karfly/chatgpt_telegram_bot#33]
I cannot find the corresponding image in the Docker on Synology NAS, which image I can looking for? Please help me.Thx

**Comment by karfly** [comment]
Docker image is built from Dockerfile. See README

**Comment by i-iooi-i** [comment]
机器人看上去很棒，是否可以考虑发布在 hub.docker 上一份呢？

**Comment by Jacky-Bruse** [comment]
I am looking forward to the release on hub.docker.

**Comment by karfly** [comment]
I think it’s not really convenient. It’s better to build it yourself
