### ISSUE TITLE
Is it unlimited?

### ISSUE THREAD

**Issue by whatthejames** [karfly/chatgpt_telegram_bot#334]
Sir do your bot use official chatgpt api.?
I mean if then we can't use it for unlimited responses.

**Comment by karfly** [comment]
Unlimited means that if you use your own OpenAI api key, you can use as much as you wish. No daily limits and so on...

**Comment by whatthejames** [comment]
> Unlimited means that if you use your own OpenAI api key, you can use as much as you wish. No daily limits and so on...

I mean can I use unofficial api to bypass free 18$ limit...
Please make changes to bypass it... Or use built-in bypass method to use without api...
Thanks for responding sir.😍

**Comment by xiangyingchang** [comment]
Hello, can I use my own API anywhere without using a VPN?

**Comment by jammesop007** [comment]
> Hello, can I use my own API anywhere without using a VPN?

You have to use proxy api to do so.

**Comment by xiangyingchang** [comment]
> 

thx
