### ISSUE TITLE
How to deploy the service on a remote host?

### ISSUE THREAD

**Issue by xjqianqian** [karfly/chatgpt_telegram_bot#335]
I'm new to running code on a remote host. I try to input the same command described in **Setup** to the console of droplet of DigitalOcean. 

Even with successful running notice shown, in the telegram, no matter what question I input, the reponse is only "...". 

See the sucessful running noitce:
![image](https://github.com/karfly/chatgpt_telegram_bot/assets/130257549/11e6fde7-1ab4-4c3b-9f6f-cf8a3ee8e005)

**Comment by karfly** [comment]
Can you show full log?

**Comment by xjqianqian** [comment]
Here is log in text:
mongo-express           | 
mongo-express           | (node:6) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
mongo-express           | Could not connect to database using connectionString: mongodb://mongo:27017/chatgpt_telegram_bot"
mongo-express           | (node:6) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: connect ECONNREFUSED 172.18.0.3:27017
mongo-express           |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
mongo-express           |   name: 'MongoNetworkError'
mongo-express           | }]
mongo-express           |     at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
mongo-express           |     at Pool.emit (events.js:314:20)
mongo-express           |     at /node_modules/mongodb/lib/core/connection/pool.js:564:14
mongo-express           |     at /node_modules/mongodb/lib/core/connection/pool.js:1000:11
mongo-express           |     at /node_modules/mongodb/lib/core/connection/connect.js:32:7
mongo-express           |     at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)
mongo-express           |     at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)
mongo-express           |     at Object.onceWrapper (events.js:421:26)
mongo-express           |     at Socket.emit (events.js:314:20)
mongo-express           |     at emitErrorNT (internal/streams/destroy.js:92:8)
mongo-express           |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
mongo-express           |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
mongo-express           | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
mongo-express           | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
mongo-express           | Welcome to mongo-express
mongo-express           | ------------------------
mongo-express           | 
mongo-express           | 
mongo-express           | (node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
mongo-express           | Mongo Express server listening at http://0.0.0.0:8081
mongo-express           | Server is open to allow connections from anyone (0.0.0.0)

**Comment by xjqianqian** [comment]
I did change any code in the config.env. I just rename from config.example.env to config.env.  Shall I update any lines in cofig.env so that the host on droplet might work? Thanks.

**Comment by xjqianqian** [comment]
It's working now. Somehow, I need to installed the dependencies Docker and Docker Compose mannually. Or this what a experienced developper shall normally do. :)
