### ISSUE TITLE
Issue after following the steps

### ISSUE THREAD

**Issue by Pratyay-ops** [karfly/chatgpt_telegram_bot#336]
I am a beginner guy I just wanted to learn how to make it work then how to make it but I couldn't deploy it even after following the 4 instructions given but still after a new api key , token from botfather I see
`mongo                 | {"t":{"$date":"2023-07-18T08:10:05.856+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn4","msg":"client metadata","attr":{"remote":"172.19.0.3:40394","client":"conn4","doc":{"driver":{"name":"PyMongo","version":"4.3.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.19.0-46-generic"},"platform":"CPython 3.8.17.final.0"}}}
chatgpt_telegram_bot  | Something went wrong during completion. Reason: You exceeded your current quota, please check your plan and billing details.`

**Comment by Pratyay-ops** [comment]
I just said I made A new api key , I believe that would grant me atleast 50 requests , I knew this would be the first place to check but it couldn't happen 
![image](https://github.com/karfly/chatgpt_telegram_bot/assets/129536170/9ad843a8-1837-47db-b0e2-5585708a1ddf)

**Comment by karfly** [comment]
No, quota is for the whole account not for a separate key

**Comment by Pratyay-ops** [comment]
it doesn't refresh everyday?

**Comment by karfly** [comment]
As far as know – no
