### ISSUE TITLE
services.mongo.ports is invalid: Invalid port "27017  # MongoDB port:27017  # MongoDB port", should be 

### ISSUE THREAD

**Issue by DimaRazb** [karfly/chatgpt_telegram_bot#35]
Hello, I got the error after running:

azr@U002:~/chatgpt_telegram_bot$ docker-compose --env-file config/config.env up --build
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mongo.ports is invalid: Invalid port "27017  # MongoDB port:27017  # MongoDB port", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.mongo_express.ports is invalid: Invalid port "8081  # Mongo Express port:8081  # Mongo Express port", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

Any thoughts what's going wrong? Thanks!

**Comment by karfly** [comment]
Can you show your config.env?

**Comment by DimaRazb** [comment]
I believe it's default one:

az@vm:~/chatgpt_telegram_bot/config$ cat config.env
MONGODB_PATH=./mongodb  # local path where to store MongoDB
MONGODB_PORT=27017  # MongoDB port

MONGO_EXPRESS_PORT=8081  # Mongo Express port
MONGO_EXPRESS_USERNAME=username  # Mongo Express username
MONGO_EXPRESS_PASSWORD=password  # Mongo Express password

**Comment by karfly** [comment]
Looks good. Maybe you have old version of docker/docker-compose?

**Comment by Jacky-Bruse** [comment]
Have  you solved this problem? I have the same problem now.

**Comment by langtuhodo** [comment]
> Hello, I got the error after running:
> 
> azr@U002:~/chatgpt_telegram_bot$ docker-compose --env-file config/config.env up --build ERROR: The Compose file './docker-compose.yml' is invalid because: services.mongo.ports is invalid: Invalid port "27017 # MongoDB port:27017 # MongoDB port", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol] services.mongo_express.ports is invalid: Invalid port "8081 # Mongo Express port:8081 # Mongo Express port", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
> 
> Any thoughts what's going wrong? Thanks!

try this way:
in line 9 change to: - "27017:27017"
in line 9 change to: - "8081:8081"

**Comment by DimaRazb** [comment]
I changed docker-compose and it worked!
I think I used version 1.29.2-1 previously, so I tested with v.20 and it started with no issues.
```
Command 'docker-compose' not found, but can be installed with:
sudo snap install docker          # version 20.10.17, or
sudo apt  install docker-compose  # version 1.29.2-1

```

But after starting I got this error:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/29647985/218185709-e7293a37-273e-4d45-8580-3e6bcc5afd65.png">

**Comment by DimaRazb** [comment]
Please ignore me guys, I forgot to use /new.
All good, the issue was in the wrong docker-compose version.
