### ISSUE TITLE
чо он хочет

### ISSUE THREAD

**Issue by DARVINGL** [karfly/chatgpt_telegram_bot#353]
"C:\Program Files\Python311\python.exe" C:\Users\Даниил\Desktop\chatgpt_telegram_bot-1.4\bot\bot.py 
C:\Program Files\Python311\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by DARVINGL** [comment]
ror 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение, Timeout: 30s, Topology Description: &lt;TopologyDescription id: 64de6f38857b36826fff57b4, topology_type: Unknown, servers: [&lt;ServerDescription (&#x27;mongo&#x27;, 27017) server_type: Unknown, rtt: None, error=AutoReconnect(&#x27;mongo:27017: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение&#x27;)&gt;]&gt;
</pre>

**Comment by karfly** [comment]
Do you use docker?
