### ISSUE TITLE
How to run on the server and give yourself tokens

### ISSUE THREAD

**Issue by slezkinis** [karfly/chatgpt_telegram_bot#354]
Решил попробовать запустить бота на сервере, но никак не могу выдать себе токенов. Может кто-то знает, как это сделать?

**Comment by slezkinis** [comment]
I decided to try to run the bot on the server, but I just can't give myself tokens. Maybe someone knows how to do it?

**Comment by skippetr** [comment]
Ты это ищешь?
https://platform.openai.com/docs/quickstart/adjust-your-settings
