### ISSUE TITLE
Something went wrong during completion. Reason: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by elliclee** [karfly/chatgpt_telegram_bot#36]
After install the bot, when I type the order on telegram, I got the wrong response: Something went wrong during completion. Reason: 'NoneType' object is not subscriptable

How could I fix this issue. Thanks.

**Comment by HaoHan9717** [comment]
How did you fix it? I had the same problem.

**Comment by HaoHan9717** [comment]
@elliclee
