### ISSUE TITLE
Mongo db is open to all?

### ISSUE THREAD

**Issue by cookins** [karfly/chatgpt_telegram_bot#366]
Hey there.
Im getting warning when composing container:
`mongo-express           | Server is open to allow connections from anyone (0.0.0.0)`
Is it really should be like that? I think it must be opened only to localhost, no?

**Comment by karfly** [comment]
Hi, it's open for anyone.
I personally host it on AWS and there I have all my ports (except ssh port) closed, so all services are not open to anybody on the Internet.

**Comment by cookins** [comment]
> Hi, it's open for anyone.
> I personally host it on AWS and there I have all my ports (except ssh port) closed, so all services are not open to anybody on the Internet.

I thought only script itself using db... is telegram api got option to use db?

**Comment by karfly** [comment]
Hmm, no. Only script itself uses MongoDB

**Comment by cookins** [comment]
> Hmm, no. Only script itself uses MongoDB

Then db must be only accessed by localhost. It's supposed to be important, no? What data exactly stored in db? Like conversations?

**Comment by karfly** [comment]
Yes, you're right
