### ISSUE TITLE
set a telegram user_name but not take effect

### ISSUE THREAD

**Issue by zhujinwei0527123** [karfly/chatgpt_telegram_bot#38]
![图片](https://user-images.githubusercontent.com/90101420/218262084-87c99584-751f-4101-8716-d55f960b0d69.png)

look at my config.yml settings file above,i set Luxian to config.yml file
after start docker-compose,my another telegram still chat with my bot?

**Comment by karfly** [comment]
Did you re-build docker after changing config file?

**Comment by heer999** [comment]
{allowed_telegram_usernames: [sisile] or  ["sisile"]  or [@sisile]# if empty, the bot is available to anyone} docker startup fails,

the correct one is？
