### ISSUE TITLE
Something went wrong during completion. Reason: module 'openai' has no attribute 'error'

### ISSUE THREAD

**Issue by topisun** [karfly/chatgpt_telegram_bot#391]
Menu buttons working fine, but after message to bot sent - this is the answer
**Something went wrong during completion. Reason: module 'openai' has no attribute 'error'**
I believe it is becouse of updates in opanai python package...

**Comment by KillingNature** [comment]
Reinstall bot from repository. Make sure that you use all new configs. Setup it completely
