### ISSUE TITLE
Slow generation and timeouts

### ISSUE THREAD

**Issue by mckbrchill** [karfly/chatgpt_telegram_bot#393]
Hello!
I've been using your bot for 2 months deployed locally with docker compose, and it seems that the generation speed lowered a week ago and also I got timeout errors sometimes. Can It be caused by new release of openai library? They have updated methods for async requests.

I tried to refactor the openai_utils.py code to use new version of lib, but it didn't help with generation speed

**Comment by mckbrchill** [comment]
I've checked it with "gpt-3.5-turbo-1106", it works much faster, I guess I should just switch to it
Issue can be closed

**Comment by karfly** [comment]
You must have used GPT-4, which is really slow. I've just added support of GPT-4 Turbo – it's much faster than GPT-4. Try it :)
