### ISSUE TITLE
hello issue with module telegram

### ISSUE THREAD

**Issue by dan1dan12345678** [karfly/chatgpt_telegram_bot#4]
hatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 0
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 0
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 1
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 1
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 1
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 1

**Comment by karfly** [comment]
Did you run command `docker compose up --build`?

**Comment by dan1dan12345678** [comment]
thanks for fast reply

here is the all track of command

chatgpt_telegram_bot git:(main) ✗ sudo docker compose up --build           
[+] Building 0.9s (9/9) FINISHED                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                      0.1s
 => => transferring context: 2B                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim                                                                                                     0.5s
 => [1/4] FROM docker.io/library/python:3.8-slim@sha256:cb29e6c698261ba263f0742524fd60dfd8a6b548fb6477a1305816e386baa4ee                                               0.0s
 => [internal] load build context                                                                                                                                      0.1s
 => => transferring context: 2.15kB                                                                                                                                    0.0s
 => CACHED [2/4] RUN mkdir -p /code                                                                                                                                    0.0s
 => CACHED [3/4] ADD . /code                                                                                                                                           0.0s
 => CACHED [4/4] WORKDIR /code                                                                                                                                         0.0s
 => exporting to image                                                                                                                                                 0.0s
 => => exporting layers                                                                                                                                                0.0s
 => => writing image sha256:6fa0a43a86465edec31ebff9797b3d6d36d1d6a3726aaf7cd3fb6949a095c7cc                                                                           0.0s
 => => naming to docker.io/library/chatgpt_telegram_bot-llm_telegram_bot                                                                                               0.0s
[+] Running 1/0
 ⠿ Container chatgpt_telegram_bot  Created                                                                                                                             0.0s
Attaching to chatgpt_telegram_bot
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 0
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 0
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 1
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 1
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 1
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot.py", line 8, in <module>
chatgpt_telegram_bot  |     from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
chatgpt_telegram_bot  | ModuleNotFoundError: No module named 'telegram'
chatgpt_telegram_bot exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)

**Comment by karfly** [comment]
Strange behavior. Looks like not all the lines in Dockerfile execute.

Try to clear cache with command `docker builder prune` and then run docker compose.
