### ISSUE TITLE
chatgpt_telegram_bot exited with code 1

### ISSUE THREAD

**Issue by goutC** [karfly/chatgpt_telegram_bot#40]
log:

....
chatgpt_telegram_bot  | The above exception was the direct cause of the following exception:
chatgpt_telegram_bot  | 
chatgpt_telegram_bot  | Traceback (most recent call last):
chatgpt_telegram_bot  |   File "bot/bot.py", line 259, in <module>
chatgpt_telegram_bot  |     run_bot()
chatgpt_telegram_bot  |   File "bot/bot.py", line 255, in run_bot
chatgpt_telegram_bot  |     application.run_polling()
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 618, in run_polling
chatgpt_telegram_bot  |     return self.__run(
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 768, in __run
chatgpt_telegram_bot  |     raise exc
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 759, in __run
chatgpt_telegram_bot  |     loop.run_until_complete(self.initialize())
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
chatgpt_telegram_bot  |     return future.result()
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 319, in initialize
chatgpt_telegram_bot  |     await self.bot.initialize()
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 375, in initialize
chatgpt_telegram_bot  |     await self.get_me()
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 238, in decorator
chatgpt_telegram_bot  |     result = await func(*args, **kwargs)
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 545, in get_me
chatgpt_telegram_bot  |     result = await self._post(
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/_bot.py", line 310, in _post
chatgpt_telegram_bot  |     return await request.post(
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 160, in post
chatgpt_telegram_bot  |     result = await self._request_wrapper(
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 279, in _request_wrapper
chatgpt_telegram_bot  |     raise exc
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 269, in _request_wrapper
chatgpt_telegram_bot  |     code, payload = await self.do_request(
chatgpt_telegram_bot  |   File "/usr/local/lib/python3.8/site-packages/telegram/request/_httpxrequest.py", line 195, in do_request
chatgpt_telegram_bot  |     raise NetworkError(f"httpx HTTPError: {err}") from err
chatgpt_telegram_bot  | telegram.error.NetworkError: httpx HTTPError: 
mongo                 | {"t":{"$date":"2023-02-12T00:03:00.961+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn22","msg":"Interrupted operation as its client disconnected","attr":{"opId":2317}}
mongo                 | {"t":{"$date":"2023-02-12T00:03:00.962+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn22","msg":"Connection ended","attr":{"remote":"172.18.0.4:59144","uuid":"86276229-d956-479b-a756-90b6c8c19b46","connectionId":22,"connectionCount":2}}
mongo                 | {"t":{"$date":"2023-02-12T00:03:01.005+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn23","msg":"Connection ended","attr":{"remote":"172.18.0.4:59146","uuid":"0f9dbfe4-6e35-468c-81ff-913d32753c53","connectionId":23,"connectionCount":1}}
chatgpt_telegram_bot exited with code 1
....

**Comment by hustnzj** [comment]
Have you solved this issue?

**Comment by Adiolph** [comment]
Same to me. Feels like some network problem in China.
