### ISSUE TITLE
Everything went well, but "NoneType" error threw

### ISSUE THREAD

**Issue by xxfelix** [karfly/chatgpt_telegram_bot#44]
The error  replied in telegram:"Something went wrong during completion. Reason: 'NoneType' object is not subscriptable"

**Comment by karfly** [comment]
Need more context to help you. Can you provide full error message and what actions led to this error?

**Comment by HUZAKI-PROJECT** [comment]
![image](https://user-images.githubusercontent.com/48891138/218477132-c5c7027a-da2c-4f1d-adf9-bb230a45f1e9.png)

**Comment by 77136975** [comment]
I have the same problem

**Comment by 77136975** [comment]
> I have the same problem

But after I used /mode to select one of the modes, it became normal

**Comment by lovecastle** [comment]
> Try to add some print messages to your code and find out where you get None exactly

Hi sir, how to print a message like "Please use command /new to start a new conversation" when this error occur? Sometime my bot send this message and make my users confused. 

Thank you for your help! Very helpful tool!
