### ISSUE TITLE
[FeatureRequest] Can we support more database to store the message?

### ISSUE THREAD

**Issue by chraac** [karfly/chatgpt_telegram_bot#45]
Recently, I found this awesome project which can integrate the chatgpt into teleggram, and I was instantly install and run it on some of my server which run pretty good.
But also, I found that we'll rely on the mongodb and mongo-express, which take lots of disk space, to store messages.
So I'm wandering if we could supports some light weight database like sqlite instead of mongo; this difinitely can save some disk space and make the install less painful on the budget vps.
Thanks!

**Comment by karfly** [comment]
Does mongo really takes a lot of disk space?

**Comment by chraac** [comment]
> Does mongo really takes a lot of disk space?

For my case, the answer is yes. I've a vps with 5gb disk space, after pulling the docker image, it'll eat up ~2gb, and the linux system needs 1gb itself, s the empty space will be < 2gb, which is insufficient for some software like npm

**Comment by karfly** [comment]
Tbh, I'm not going to switch from Mongo, but working PR with (e.g.) sqlite will be great

**Comment by chraac** [comment]
> Tbh, I'm not going to switch from Mongo, but working PR with (e.g.) sqlite will be great

Sure, I will draft a PR about it

**Comment by chraac** [comment]
> Tbh, I'm not going to switch from Mongo, but working PR with (e.g.) sqlite will be great

Hi @karfly, drafted a PR for adding the sqlite database, PTAL

**Comment by wy580477** [comment]
> Sure, I will draft a PR about it

I have built an alpine-based image with your sqlite support code. 

https://github.com/wy580477/chatgpt_telegram_bot

Image size is only 65MB.

**Comment by chraac** [comment]
> Hi, I decided not to add addition db support to the project not to confuse repo users. You can keep it as a separate repo code!

Okay, then I'll make my forked repo up to date manually
