### ISSUE TITLE
[ERROR] config.env

### ISSUE THREAD

**Issue by akynazh** [karfly/chatgpt_telegram_bot#46]
If comment like this:
```
MONGODB_PATH=./mongodb # local path where to store MongoDB
MONGODB_PORT=27017 # MongoDB port
```

Then in some system, mongo path will be "./mongodb # local path where to store MongoDB" and port will be "27017 # MongoDB port", which could not be specified.

So I think config.env should be:

```
# local path where to store MongoDB
MONGODB_PATH=./mongodb
# MongoDB port
MONGODB_PORT=27017

# Mongo Express port
MONGO_EXPRESS_PORT=8081
# Mongo Express username
MONGO_EXPRESS_USERNAME=username
# Mongo Express password
MONGO_EXPRESS_PASSWORD=password
```

Comments should not be placed after the variable.

**Comment by karfly** [comment]
Thank you for your note! Can you please make a PR with these changes?

**Comment by akynazh** [comment]
> Thank you for your note! Can you please make a PR with these changes?

sure

**Comment by karfly** [comment]
MERGED! Thank you @akynazh! ❤️
