### ISSUE TITLE
Some problems at runtime

### ISSUE THREAD

**Issue by bangenlanbai** [karfly/chatgpt_telegram_bot#47]
Thank you for providing this library!

- `config.example.env` : Cannot have comments `#` The following should be deleted
- `Dockerfile`:
   1. add `RUN python -m pip install --upgrade pip` 
   2. add `RUN pip3 install -r requirements.txt --root-user-action=ignore`
   3. add `ENV PIP_ROOT_USER_ACTION=ignore`
#### `example file` : 

1. https://github.com/bangenlanbai/chatgpt_telegram_bot/blob/main/Dockerfile
2. https://github.com/bangenlanbai/chatgpt_telegram_bot/blob/main/config/config.example.env

**Comment by zanderzhng** [comment]
I'm good with the env and the dockerfile.
