### ISSUE TITLE
issues on install and usage, object non subscriptable

### ISSUE THREAD

**Issue by FuriousFowl** [karfly/chatgpt_telegram_bot#49]
mongo                   | {"t":{"$date":"2023-02-16T14:31:41.464+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"conn4","msg":"Index build: done building","attr":{"buildUUID":null,"collectionUUID":{"uuid":{"$uuid":"xxx"}},"namespace":"chatgpt_telegram_bot.user","index":"_id_","ident":"index-8--6246329400734996252","collectionIdent":"collection-7--6246329400734996252","commitTimestamp":null}}
chatgpt_telegram_bot    | Something went wrong during completion. Reason: 'NoneType' object is not subscriptable
chatgpt_telegram_bot    | Something went wrong during completion. Reason: 'NoneType' object is not subscriptable
chatgpt_telegram_bot    | Something went wrong during completion. Reason: 'NoneType' object is not subscriptable
chatgpt_telegram_bot    | Something went wrong during completion. Reason: 'NoneType' object is not subscriptable

**Comment by gooderek** [comment]
restart
