### ISSUE TITLE
Is it possible to add serverless hosting providers compatiblity?

### ISSUE THREAD

**Issue by gooderek** [karfly/chatgpt_telegram_bot#52]
for those who dont have a VPS?

**Comment by karfly** [comment]
Not really familiar with this topic. Can you share any examples?

**Comment by gooderek** [comment]
> Not really familiar with this topic. Can you share any examples?
some repos can be connected to those platforms(e.g., railway.app, render.com...) directly,  and deloyed easily for noobs:
https://github.com/pyfbsdk59/Golang-ChatGPT-TelegramBot-Render
or
https://github.com/habitual69/ChatGPT-TelegramBot

**Comment by gooderek** [comment]
> Not really familiar with this topic. Can you share any examples?

**Comment by kuzyara** [comment]
@gooderek https://github.com/franalgaba/chatgpt-telegram-bot-serverless

**Comment by xingfanxia** [comment]
+1, basically the problems with those platforms is that they don't support dockercompose. So will have to everything in one docker container with supervisord
