### ISSUE TITLE
Important notice from DigitalOcean regarding a potentially misconfigured MongoDB

### ISSUE THREAD

**Issue by lovecastle** [karfly/chatgpt_telegram_bot#65]
Hello,
I've just received a message from DigitalOcean where I setup an Ubuntu vps for my chatGPT telegram bot. They said:

> "A recent network security scan suggests your Droplet chatGPT is running a MongoDB instance and that it may be unintentionally exposing data, or misconfigured to allow unauthorized access.    
> 
> MongoDB listens for traffic from everywhere on port 27107 and you can validate this report by attempting to connect to your MongoDB instance on  via a simple telnet command: 	 	
> 
> 	telnet ***.***.***.*** 27107   
> 
> If the connection is successful you will receive output like the following, which will confirm that your service is visible to the public Internet:   	
> 
> 	Trying ***.***.***.*** ... 	
> 	Connected to ***.***.***.*** . 	
> 	Escape character is '^]'.   
> 
> You will want to restrict access to your MongoDB instance to prevent outsiders from reading or modifying your data. "

I don't want to block traffic by IP, how can I increase the security for this issue?

**Comment by wy580477** [comment]
You don‘t need to expose mongo container's 27107 port. 

Delete mongo's ports section in docker-compose file.
