### ISSUE TITLE
Gpt-3.5-turbo API

### ISSUE THREAD

**Issue by djx2726889** [karfly/chatgpt_telegram_bot#68]
Hello, OpenAI just release the gpt-3.5-turbo API, can you support it?

**Comment by muzhi1991** [comment]
Request a new model

**Comment by karfly** [comment]
Yes, guys. Working on it!

**Comment by Andy963** [comment]
i have updated to the gpt-3.5-turbo, but i change the database to sqlite, and i'm not good at docker things,  so can't pr

**Comment by karfly** [comment]
I've just added support of ChatGPT API. Commit: https://github.com/karfly/chatgpt_telegram_bot/commit/0779808db35e99541002b7d3aadf82d890797738

@djx2726889 @muzhi1991 @Andy963 @XGZepto @EsqerYasen @N0ne1eft @songyp0505 @rainux
It would be great if you tested it, guys!

**Comment by djx2726889** [comment]
> I've just added support of ChatGPT API. Commit: [0779808](https://github.com/karfly/chatgpt_telegram_bot/commit/0779808db35e99541002b7d3aadf82d890797738)
> 
> @djx2726889 @muzhi1991 @Andy963 @XGZepto @EsqerYasen @N0ne1eft @songyp0505 @rainux Guys, it would be great if you tested it and share your feedback!

It seems to be working fine. Many thanks for your excellent work!

**Comment by muzhi1991** [comment]
> I've just added support of ChatGPT API. Commit: [0779808](https://github.com/karfly/chatgpt_telegram_bot/commit/0779808db35e99541002b7d3aadf82d890797738)↳
> 
> @djx2726889 @muzhi1991 @Andy963 @XGZepto @EsqerYasen @N0ne1eft @songyp0505 @rainux Guys, it would be great if you tested it and share your feedback!↳

it works perfectly when i build image from scratch

**Comment by xqa** [comment]
![Snipaste_2023-03-04_15-57-51](https://user-images.githubusercontent.com/107579458/222884515-a5b3b2f6-cbcb-43ac-8c5a-457936a1345e.png)
![Snipaste_2023-03-04_15-56-55](https://user-images.githubusercontent.com/107579458/222884518-e627a23d-b61e-4997-ae33-b4831428392b.png)
![Snipaste_2023-03-04_15-56-13](https://user-images.githubusercontent.com/107579458/222884520-322218ee-1c8f-4e18-8d8a-afd58e2c561e.png)
There is a small problem here, if I am modifying `
Gpt-3.5-turbo` has been used before, and the `n_spent_dollars` calculated here is wrong

**Comment by karfly** [comment]
@xqa 
You're right, it's not correct. Anyway, I don't want to add more entity to db regarding `n_used_tokens` for different engines

**Comment by xqa** [comment]
> @xqa You're right, it's not correct. Anyway, I don't want to add more entity to db regarding `n_used_tokens` for different engines

The best way is to get this data through openai api instead of calculation. Now this does not affect the use

**Comment by karfly** [comment]
Can you show, how to see spent dollars with API?

**Comment by xqa** [comment]
> Can you show, how to see spent dollars with API?

My fault is that I didn't express clearly, I mean if there is this API.  I didn't find it either, maybe openai will add it in the future

**Comment by karfly** [comment]
Okay, got what you meant
