### ISSUE TITLE
can i have some help please

### ISSUE THREAD

**Issue by Mata23K77** [karfly/chatgpt_telegram_bot#71]
![Screenshot_4](https://user-images.githubusercontent.com/121389119/222535808-49ea39a0-27fe-4b68-87eb-7260b7c6c62d.png)

what should I do here?

**Comment by Mata23K77** [comment]
oh wait.. its build not rebuild .....

**Comment by Mata23K77** [comment]
update: the same error with --build

**Comment by karfly** [comment]
Hi. Try googling: "docker-compose is not recognized as the name of a cmdlet". It's a core problem
