### ISSUE TITLE
Code highlighting dosen't work 

### ISSUE THREAD

**Issue by scriptedjuice** [karfly/chatgpt_telegram_bot#77]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/37115370/222777746-aed7c829-6371-4bc9-8f87-2c820505f398.png">

Syntax wrapped in quotes but not highlighted

**Comment by scriptedjuice** [comment]
You need use code mode

**Comment by superman66** [comment]
hi @scriptedjuice, I met the same issue. But I was wondering, what is code mode?
I choose `ChatGPT code assistant`, but the code highlighting still doesn't work.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/12592949/222875317-42dd7865-68a4-4fc5-b1ab-e822b0aa3201.png">
