### ISSUE TITLE
Something went wrong during completion. Reason: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by fqw000** [karfly/chatgpt_telegram_bot#78]
mongo-express         | Mongo Express server listening at http://0.0.0.0:8081
mongo-express         | Server is open to allow connections from anyone (0.0.0.0)
mongo                 | {"t":{"$date":"2023-03-04T05:13:52.593+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.4:51322","uuid":"e0994f27-2006-4d7e-9560-9b2e2eac37ed","connectionId":4,"connectionCount":4}}
mongo                 | {"t":{"$date":"2023-03-04T05:13:52.595+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn4","msg":"client metadata","attr":{"remote":"172.18.0.4:51322","client":"conn4","doc":{"driver":{"name":"PyMongo","version":"4.3.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"4.18.0-408.el8.x86_64"},"platform":"CPython 3.8.16.final.0"}}}
chatgpt_telegram_bot  | Something went wrong during completion. Reason: 'NoneType' object is not subscriptable

**Comment by wy580477** [comment]
Need to select a mode first.

**Comment by fqw000** [comment]
it works
