### ISSUE TITLE
(f"User {user_id} does not exist")

### ISSUE THREAD

**Issue by Floppik** [karfly/chatgpt_telegram_bot#8]
Hi! I try to set up bot, but i always give the same error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 945, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 135, in handle_update
    return await self.callback(update, context)
  File "bot/bot.py", line 137, in new_dialog_handle
    db.set_user_attribute(user_id, "last_interaction", datetime.now())
  File "/code/bot/database.py", line 90, in set_user_attribute
    self.check_if_user_exists(user_id, raise_exception=True)
  File "/code/bot/database.py", line 23, in check_if_user_exists
    raise ValueError(f"User {user_id} does not exist")
ValueError: User 300300302 does not exist
```
My config.yml :
allowed_telegram_usernames: [Username]  # if empty, the bot is available to anyone
I also try:
allowed_telegram_usernames: [300300302]  # if empty, the bot is available to anyone
allowed_telegram_usernames: ["Username"]  # if empty, the bot is available to anyone
allowed_telegram_usernames: []  # if empty, the bot is available to anyone

But this no effect

**Comment by karfly** [comment]
Hmm.
Try to run command `/start` in bot to register user.

**Comment by Floppik** [comment]
Thanks!

**Comment by karfly** [comment]
BTW, the latest commit (1681b4bd1c6dcd644c25d35473bee91b64c81c25) solves your initial problem. Now user can be registered from any handler.

**Comment by karfly** [comment]
OpenAI can't be used on free plan. You need to pay for it.
