### ISSUE TITLE
Something went wrong during completion. Reason: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Mrvivi** [karfly/chatgpt_telegram_bot#81]
how to fix my problem , bro ? thanks for your help ! 
<img width="713" alt="Snipaste_2023-03-04_23-55-53" src="https://user-images.githubusercontent.com/49402255/222915996-09bd0839-da46-43ab-a52c-5b03a7ba977d.png">

<img width="584" alt="Snipaste_2023-03-04_23-48-01" src="https://user-images.githubusercontent.com/49402255/222916003-b3063544-faff-4e3b-83d2-1676eb82763c.png">

**Comment by karfly** [comment]
This error constantly haunts us and I can never understand its root cause. Can you reproduce it?

**Comment by karfly** [comment]
Finally fixed it in https://github.com/karfly/chatgpt_telegram_bot/commit/ce29dfd044b3834a234e3de121863fecd4525868! Get updated.

**Comment by Mrvivi** [comment]
yes, fixed it . really good ! thank you ! can you tell me how to keep it running in backstage? the telegram bot only answer me during "docker-compose --env-file config/config.env up --build" working , when i press "Ctrl+C", it stops .

**Comment by karfly** [comment]
Thank you. You can add `-d` option  to make docker work in background
