### ISSUE TITLE
How to add menu button? 

### ISSUE THREAD

**Issue by Oranzh** [karfly/chatgpt_telegram_bot#84]
I want to add the buttons as yours, and the links are? Thanks ur reply.

**Comment by socalledPF** [comment]
botfather里面操作bot添加command。

**Comment by Oranzh** [comment]
你好，这个需要具体的链接？有button对应的链接吗？

socalledPF ***@***.***> 于 2023年3月5日周日 下午10:24写道：

**Comment by karfly** [comment]
1. Go to [@BotFather](t.me/BotFather)
2. /mybots -> {bot} -> Edit Bot -> Edit Commands
3. Send this text:
```
retry - Regenerate last bot answer
new - Start new dialog
mode - Select chat mode
balance - Show balance
help - Show help
```

**Comment by Oranzh** [comment]
Thank you very much for your reply.
