### ISSUE TITLE
Use MARKDOWN_V2 parser instead of HTML parser.

### ISSUE THREAD

**Issue by zanderzhng** [karfly/chatgpt_telegram_bot#86]
Use markdown replies instead of htmls, especially for the replies from chatgpt api.

I replaced all the ParseMode.HTML with ParseMode.MARKDOWN_V2 and get "Some error in error handler", but I'm not sure how to debug it yet.

It would be great if you can help.

**Comment by karfly** [comment]
Hi!
Just tested it and it really works better with markdown. I'll fix it

**Comment by karfly** [comment]
Fixed here: 15e4ec513a3fc336e75b2e84a603982ffac47356
