### ISSUE TITLE
[Feature] Import more chat_modes

### ISSUE THREAD

**Issue by kagwind** [karfly/chatgpt_telegram_bot#87]
Would you consider providing an easy approach to import more chat modes to the bot?
For example, the following GitHub project includes prompts to ask ChatGPT to act as some useful roles:
https://github.com/f/awesome-chatgpt-prompts#act-as-an-english-translator-and-improver

**Comment by fedosov** [comment]
Please also have a look at PR which allows adding modes via config file: https://github.com/karfly/chatgpt_telegram_bot/pull/76

**Comment by karfly** [comment]
@kagwind @fedosov
Next, I'm planning to add DALLE-2 support. Then I'll transfer modes from code to configs (I'll use @fedosov's code) and then add new cool modes. Maybe I'll even make some challenge for best created modes 🥇

**Comment by karfly** [comment]
I made separate config file for Chat Modes (15e4ec513a3fc336e75b2e84a603982ffac47356)

@fedosov @kagwind 
Guys, it'd be great, if you tested it!

**Comment by kagwind** [comment]
Thanks for the update. It works great! 
Now it is easy to add more interesting modes to the bot.

But I wonder is there a typo on Line 26 in chat_modes.yml (an extra ")?

**Comment by karfly** [comment]
@kagwind thank you, fixed: 2248a2bd92fec8a3d504efbd83c69071375464dc
