### ISSUE TITLE
How to update easily?

### ISSUE THREAD

**Issue by CCCAUCHY** [karfly/chatgpt_telegram_bot#88]
I am not familiar with Docker. Is it sufficient to update this project by first cloning the repository with `git clone` and then building the Docker images with` docker-compose --build`?

It seems if I remove the directory first without `docker-compose down` then the docker can not be kill forever

**Comment by wy580477** [comment]
I built a ready-to-use image: https://github.com/wy580477/chatgpt_telegram_bot

You can just pull my image to keep up new changes.

**Comment by wy580477** [comment]
I don't why author doesn't offer a ready-to-use image.

I built one myself with alpine base-image and sqlite database instead of mongo:

https://github.com/wy580477/chatgpt_telegram_bot

**Comment by karfly** [comment]
Command `docker-compose up --build` first takes down running docker containers and then setups new ones

**Comment by madiele** [comment]
if you already have the git repo in the folder remember to also do a `git pull` before the `docker-compose` command

**Comment by im6h** [comment]
You can use `docker-compose up --build` to only build the newest image (if you have changed code) or then use `docker-compose up -d` to build and then run the image. If you are not familiar with `docker` platform, run it with setup `python:3.8`, `mongodb`. Run `docker-compose down` in the folder containing `docker-compose.yml` to down all service-container declared in this file.
