### ISSUE TITLE
Hello! Need your help

### ISSUE THREAD

**Issue by Pablito228** [karfly/chatgpt_telegram_bot#9]
Karim. Good evening. Will you help me with starting script? I`m кефирчик at coding and don`t know, how can i start the script. Also when i using mv config/config.example.yml config/config.yml i got an error "The System Cannot Find The Path Specified"

**Comment by karfly** [comment]
Hi, tbh it'll be difficult to run the code without knowledge of terminal.
The command you tried to run must be executed from the repo dir. So, go to repo dir using `cd` command and then run the command.

**Comment by Pablito228** [comment]
У меня в целом всё получилось, устанавливается ща всё. Вопрос - можно ли сделать так, чтобы ChatGPT отвечал исключительно на русском?

**Comment by karfly** [comment]
Yes, you need to rewrite prompts in `bot/chatgpt.py` in any language you want. But I think it'll work worse.

**Comment by nikolabate** [comment]
Please make this without docker, just python.

**Comment by karfly** [comment]
Docker is more convenient for deploying
