### ISSUE TITLE
How to deploy on Replit?

### ISSUE THREAD

**Issue by ab-kaium** [karfly/chatgpt_telegram_bot#91]
How to deploy on Replit?

**Comment by pr1k0l** [comment]
I'll join the question. I tried to upload a bot to fly.io, but the service does not start for some unknown reason.

**Comment by wy580477** [comment]
> I'll join the question. I tried to upload a bot to fly.io, but the service does not start for some unknown reason.

You can use my image, it should works fine on fly.io. You just need to write a Dockfile to copy config.yml into container, than add a persistent volume to storage sqlite database.

https://github.com/wy580477/chatgpt_telegram_bot/tree/custom

**Comment by karfly** [comment]
Unfortunately, I can't help with deploying on different services. I'll keep the issue open for a while – maybe somebody will help.

**Comment by clemsau** [comment]
You should give more details about what you are stuck with/which step. 

I don't know the platforms a lot, but it seems like this app can run on both replit and fly.io

For replit for instance, you can simply copy the repository, modify the config files as indicated in the README, get into the shell, install docker & docker compose, then just run the docker compose command in the README

**Comment by rsuhfamily** [comment]
prybar-python310 not found in $PATH 😥

**Comment by ngn999** [comment]
I have deployed the bot to fly.io. If anyone wants to try it out, please take a look at this commit: https://github.com/ngn999/chatgpt_telegram_bot/commit/d41539f604772f26a9e09cabef2a790e42a66e6a
